// Code generated by protoc-gen-go-proxy. DO NOT EDIT.
// source: admin.proto

package proxypb

import (
	"context"

	"github.com/effective-security/porto/pkg/retriable"
	"github.com/effective-security/porto/xhttp/correlation"
	"github.com/effective-security/porto/xhttp/httperror"
	"github.com/effective-security/trustyca/api/pb"
	"github.com/effective-security/trustyca/privpb"
	"google.golang.org/grpc"
)

type proxyAdminServer struct {
	srv privpb.AdminServer
}

type proxyAdminClient struct {
	remote   privpb.AdminClient
	callOpts []grpc.CallOption
}

type postproxyAdminClient struct {
	client retriable.PostRequester
}

// AdminServerToClient returns privpb.AdminClient
func AdminServerToClient(srv privpb.AdminServer) privpb.AdminClient {
	return &proxyAdminServer{srv}
}

// NewAdminClient returns instance of the AdminClient
func NewAdminClient(conn *grpc.ClientConn, callOpts []grpc.CallOption) privpb.AdminServer {
	return &proxyAdminClient{
		remote:   privpb.NewAdminClient(conn),
		callOpts: callOpts,
	}
}

// NewAdminClientFromProxy returns instance of AdminClient
func NewAdminClientFromProxy(proxy privpb.AdminClient) privpb.AdminServer {
	return &proxyAdminClient{
		remote: proxy,
	}
}

// NewAdminClientFromProxy returns instance of AdminClient
func NewHTTPAdminClient(client retriable.PostRequester) privpb.AdminServer {
	return &postproxyAdminClient{
		client: client,
	}
}

func (s *proxyAdminServer) ListOrgs(ctx context.Context, req *privpb.ListOrgsRequest, opts ...grpc.CallOption) (*pb.OrgsResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.srv.ListOrgs(ctx, req)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}
func (s *proxyAdminClient) ListOrgs(ctx context.Context, req *privpb.ListOrgsRequest) (*pb.OrgsResponse, error) {
	// add correlation ID to outgoing RPC calls
	ctx = correlation.WithMetaFromContext(ctx)
	res, err := s.remote.ListOrgs(ctx, req, s.callOpts...)
	if err != nil {
		return nil, httperror.NewFromPb(err)
	}
	return res, nil
}
func (s *postproxyAdminClient) ListOrgs(ctx context.Context, req *privpb.ListOrgsRequest) (*pb.OrgsResponse, error) {
	var res pb.OrgsResponse
	path := privpb.Admin_ListOrgs_FullMethodName
	_, _, err := s.client.Post(ctx, path, req, &res)
	if err != nil {
		return nil, err
	}
	return &res, nil
}
