// Code generated by protoc-gen-go-mock. DO NOT EDIT.

package privpb

import (
	context "context"
	"net/http"

	"github.com/effective-security/porto/xhttp/httperror"
	"github.com/effective-security/porto/xhttp/marshal"
)

// RequestAllocator defines constructor to allocate Protobuf request
type RequestAllocator func() any

// CheckAccessFunc defines function to check access rights for the HTTP request
type CheckAccessFunc func(ctx context.Context, req any, action string) error

// MethodInfo provides info about RPC method
type MethodInfo struct {
	Allocator       RequestAllocator
	AllowedRoles    []string
	Scopes          []string
	CliCmd          string
	RefreshInterval uint32
}

// UnmarshalRequest unmarshals JSON body of HTTP request to protobuf request
func UnmarshalRequest(w http.ResponseWriter, r *http.Request) (any, *MethodInfo, error) {
	info := methods[r.URL.Path]
	if info == nil {
		err := httperror.NotFound("path not found: %s", r.URL.Path)
		marshal.WriteJSON(w, r, err)
		return nil, nil, err
	}

	req := info.Allocator()
	err := marshal.DecodeBody(w, r, req)
	if err != nil {
		// DecodeBody writes error response and logs, if invalid request
		return nil, nil, err
	}
	return req, info, nil
}

// GetMethodInfo returns MethodInfo
func GetMethodInfo(method string) *MethodInfo {
	return methods[method]
}

// GetMethodsInfo returns map of methods
func GetMethodsInfo() map[string]*MethodInfo {
	return methods
}

// GetMethodAliases returns map of method CLI commands to method names
func GetMethodAliases() map[string]string {
	res := make(map[string]string, len(methods))
	for fn, method := range methods {
		if method.CliCmd != "" {
			res[method.CliCmd] = fn
		}
	}
	return res
}

// methods defines map for routes
var methods = map[string]*MethodInfo{

	Admin_ListOrgs_FullMethodName: {
		Allocator: func() any { return new(ListOrgsRequest) },
		CliCmd:    "admin org list",
	},
}
