// Code generated by protoc-gen-go-json. DO NOT EDIT.

package privpb

import (
	context "context"
	"fmt"
	sync "sync"

	"github.com/effective-security/protoc-gen-go/api"
	pb "github.com/effective-security/trustyca/api/pb"
)

var NextPage_MessageDescription = &api.MessageDescription{
	Name:          "NextPage",
	Display:       "Next Page",
	FullName:      "pb.NextPage",
	Documentation: `NextPage specifies pagination information, if there are more pages to fetch.`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Offset",
			FullName:      "pb.NextPage.Offset",
			Type:          "uint32",
			SearchType:    "integer",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Offset is the offset of the next page for offset-based pagination.
Offset is limited to 10000.
To paginate for large number of records, use cursor-based pagination
instead.`,
		},
		{
			Name:          "Cursor",
			FullName:      "pb.NextPage.Cursor",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Cursor is the cursor of the next page for cursor-based pagination.
Use "initial" to start the pagination or pass the cursor returned from
this response.`,
		},
	},
}

var Org_MessageDescription = &api.MessageDescription{
	Name:     "Org",
	FullName: "pb.Org",
	Fields: []*api.FieldMeta{
		{
			Name:          "ID",
			FullName:      "pb.Org.ID",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "Alias",
			FullName:      "pb.Org.Alias",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "Name",
			FullName:      "pb.Org.Name",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "Description",
			FullName:      "pb.Org.Description",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:          "CreatedAt",
			FullName:      "pb.Org.CreatedAt",
			Display:       "Created At",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
		},
		{
			Name:            "Status",
			FullName:        "pb.Org.Status",
			Type:            "int32",
			SearchType:      "integer",
			SearchOptions:   api.SearchOption_Sortable,
			EnumDescription: pb.ItemStatus_Enum_EnumDescription,
		},
	},
}

var OrgsResponse_MessageDescription = &api.MessageDescription{
	Name:     "OrgsResponse",
	Display:  "Orgs Response",
	FullName: "pb.OrgsResponse",
	Fields: []*api.FieldMeta{
		{
			Name:       "Orgs",
			FullName:   "pb.OrgsResponse.Orgs",
			Type:       "[]struct",
			StructName: "pb.Org",
			SearchType: "flat_object",
		},
		{
			Name:       "NextPage",
			FullName:   "pb.OrgsResponse.NextPage",
			Display:    "Next Page",
			Type:       "struct",
			StructName: "pb.NextPage",
			SearchType: "flat_object",
			Documentation: `NextPage specifies pagination information, if there are more pages to
fetch. If there are no more pages to fetch, NextPage will be empty.`,
		},
	},
}

var ListOrgsRequest_MessageDescription = &api.MessageDescription{
	Name:          "ListOrgsRequest",
	Display:       "List Orgs Request",
	FullName:      "privpb.ListOrgsRequest",
	Documentation: `ListOrgsRequest specifies list orgs request`,
	Fields: []*api.FieldMeta{
		{
			Name:          "Limit",
			FullName:      "privpb.ListOrgsRequest.Limit",
			Type:          "uint32",
			SearchType:    "integer",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Limit specifies maximum number of records to return`,
		},
		{
			Name:          "Offset",
			FullName:      "privpb.ListOrgsRequest.Offset",
			Type:          "uint32",
			SearchType:    "integer",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Offset specifies offset for the offset-based pagination.
Which is limited to 10000.
To paginate for large number of records, use cursor-based pagination
instead.`,
		},
		{
			Name:          "Cursor",
			FullName:      "privpb.ListOrgsRequest.Cursor",
			Type:          "string",
			SearchType:    "keyword",
			SearchOptions: api.SearchOption_Sortable,
			Documentation: `Cursor specifies cursor for the cursor-based pagination.
Use "initial" to start the pagination or pass the cursor returned from
the previous request.`,
		},
		{
			Name:            "Status",
			FullName:        "privpb.ListOrgsRequest.Status",
			Type:            "int32",
			SearchType:      "integer",
			SearchOptions:   api.SearchOption_Sortable,
			EnumDescription: pb.ItemStatus_Enum_EnumDescription,
			Documentation: `Status specifies on optional status of the item to filter by.
If not specified, all items will be listed.`,
		},
	},
}

// MessageAllocator defines constructor to allocate Protobuf message
type MessageAllocator func() any

var (
	initMessageDescriptionOnce sync.Once
	messageDescriptions        = map[string]*api.MessageDescription{
		"pb.NextPage":            NextPage_MessageDescription,
		"pb.Org":                 Org_MessageDescription,
		"pb.OrgsResponse":        OrgsResponse_MessageDescription,
		"privpb.ListOrgsRequest": ListOrgsRequest_MessageDescription,
	}

	messageAllocators = map[string]MessageAllocator{
		"pb.NextPage":            func() any { return new(pb.NextPage) },
		"pb.Org":                 func() any { return new(pb.Org) },
		"pb.OrgsResponse":        func() any { return new(pb.OrgsResponse) },
		"privpb.ListOrgsRequest": func() any { return new(ListOrgsRequest) },
	}
)

func (m *ListOrgsRequest) Validate(ctx context.Context) error {
	return api.ValidateRequest(ctx, m, ListOrgsRequest_MessageDescription)
}

func GetMessageDescriptions() map[string]*api.MessageDescription {
	// Update the message Fields with the nested messages
	initMessageDescriptionOnce.Do(func() {
		for _, md := range messageDescriptions {
			for _, field := range md.Fields {
				if field.Fields == nil && (field.Type == "struct" || field.Type == "[]struct" || field.Type == "object" || field.Type == "[]object") {
					if msgDescr, ok := messageDescriptions[field.StructName]; ok {
						field.Fields = msgDescr.Fields
					}
				}
			}
		}
	})
	return messageDescriptions
}

func CreateMessage(fullname string) any {
	allocator := messageAllocators[fullname]
	if allocator == nil {
		panic(fmt.Sprintf("allocator for %s not found", fullname))
	}
	return allocator()
}

func GetMessageDescription(fullname string) *api.MessageDescription {
	return GetMessageDescriptions()[fullname]
}

func init() {
	_ = GetMessageDescriptions()
}
