// Code generated by protoc-gen-go-mock. DO NOT EDIT.
// source: admin.proto

package mockpb

import (
	"context"

	"github.com/effective-security/trustyca/api/pb"
	"github.com/effective-security/trustyca/privpb"
	"google.golang.org/protobuf/proto"
)

// MockAdminServer for testing
type MockAdminServer struct {
	privpb.AdminServer

	Reqs []proto.Message

	// If set, all calls return this error.
	Err error

	// responses to return if err == nil
	Resps []proto.Message
	Index int
}

// SetResponse sets a single response without errors
func (m *MockAdminServer) SetResponse(r proto.Message) {
	m.Err = nil
	m.Resps = []proto.Message{r}
	m.Index = 0
}

// SetResponses sets responses without errors
func (m *MockAdminServer) SetResponses(r []proto.Message) {
	m.Err = nil
	m.Resps = r
	m.Index = 0
}

func (m *MockAdminServer) next() proto.Message {
	c := len(m.Resps)
	idx := m.Index
	m.Index++
	if idx >= c {
		idx = c - 1
	}
	return m.Resps[idx]
}

func (m *MockAdminServer) ListOrgs(ctx context.Context, req *privpb.ListOrgsRequest) (*pb.OrgsResponse, error) {
	if m.Err != nil {
		return nil, m.Err
	}
	return m.next().(*pb.OrgsResponse), nil
}
