---
metrics:
  disabled: true
  prometheus:
    addr:

servers:
  wfe:
    disabled: false

tasks: []

client:
  client_tls:
    cert: $(HOME)/.trustyca/certs/trustyca_client.pem
    key: $(HOME)/.trustyca/certs/trustyca_client.key
    trusted_ca: $(HOME)/.trustyca/certs/trusty_root_ca.pem
  dial_timeout: 60s
