// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: ca.proto

package httppb

import (
	"net/http"

	"github.com/effective-security/porto/restserver"
	"github.com/effective-security/porto/xhttp/correlation"
	"github.com/effective-security/porto/xhttp/httperror"
	"github.com/effective-security/porto/xhttp/marshal"
	"github.com/effective-security/trustyca/api/pb"
)

// GetCAHTTPHandler handles HTTP requests for CA service
func GetCAHTTPHandler(s pb.CAServer, withAccessCheck pb.CheckAccessFunc) restserver.Handle {
	return func(w http.ResponseWriter, r *http.Request, p restserver.Params) {
		action := r.URL.Path
		ctx := correlation.WithMetaFromRequest(r)

		var err error
		var res any

		req, _, err := pb.UnmarshalRequest(w, r)
		if err != nil {
			// UnmarshalRequest already writes error response
			return
		}

		if withAccessCheck != nil {
			err = withAccessCheck(ctx, req, action)
			if err != nil {
				marshal.WriteJSON(w, r, err)
				return
			}
		}

		switch action {

		case pb.CA_RegisterIssuer_FullMethodName:
			res, err = s.RegisterIssuer(ctx, req.(*pb.RegisterIssuerRequest))

		case pb.CA_UpdateIssuer_FullMethodName:
			res, err = s.UpdateIssuer(ctx, req.(*pb.UpdateIssuerRequest))

		case pb.CA_ImportIssuer_FullMethodName:
			res, err = s.ImportIssuer(ctx, req.(*pb.ImportIssuerRequest))

		case pb.CA_ActivateIssuer_FullMethodName:
			res, err = s.ActivateIssuer(ctx, req.(*pb.ActivateIssuerRequest))

		case pb.CA_GetIssuer_FullMethodName:
			res, err = s.GetIssuer(ctx, req.(*pb.GetIssuerRequest))

		case pb.CA_ListIssuers_FullMethodName:
			res, err = s.ListIssuers(ctx, req.(*pb.ListIssuersRequest))

		case pb.CA_RegisterRoot_FullMethodName:
			res, err = s.RegisterRoot(ctx, req.(*pb.RegisterRootRequest))

		case pb.CA_ListRoots_FullMethodName:
			res, err = s.ListRoots(ctx, req.(*pb.ListRootsRequest))

		case pb.CA_RegisterProfile_FullMethodName:
			res, err = s.RegisterProfile(ctx, req.(*pb.RegisterProfileRequest))

		case pb.CA_GetProfile_FullMethodName:
			res, err = s.GetProfile(ctx, req.(*pb.GetProfileRequest))

		case pb.CA_ListProfiles_FullMethodName:
			res, err = s.ListProfiles(ctx, req.(*pb.ListProfilesRequest))

		case pb.CA_DeleteProfile_FullMethodName:
			res, err = s.DeleteProfile(ctx, req.(*pb.DeleteProfileRequest))

		case pb.CA_SignCertificate_FullMethodName:
			res, err = s.SignCertificate(ctx, req.(*pb.SignCertificateRequest))

		case pb.CA_GetCertificate_FullMethodName:
			res, err = s.GetCertificate(ctx, req.(*pb.GetCertificateRequest))

		case pb.CA_ListCertificates_FullMethodName:
			res, err = s.ListCertificates(ctx, req.(*pb.ListCertificatesRequest))

		case pb.CA_UpdateCertificateLabel_FullMethodName:
			res, err = s.UpdateCertificateLabel(ctx, req.(*pb.UpdateCertificateLabelRequest))

		case pb.CA_RevokeCertificate_FullMethodName:
			res, err = s.RevokeCertificate(ctx, req.(*pb.RevokeCertificateRequest))

		case pb.CA_ListRevokedCertificates_FullMethodName:
			res, err = s.ListRevokedCertificates(ctx, req.(*pb.ListRevokedCertificatesRequest))

		case pb.CA_GetCRL_FullMethodName:
			res, err = s.GetCRL(ctx, req.(*pb.GetCrlRequest))

		case pb.CA_PublishCrls_FullMethodName:
			res, err = s.PublishCrls(ctx, req.(*pb.PublishCrlsRequest))

		case pb.CA_SignOCSP_FullMethodName:
			res, err = s.SignOCSP(ctx, req.(*pb.OCSPRequest))

		default:
			err = httperror.Malformed("invalid action: %s", action)
		}
		if err != nil {
			marshal.WriteJSON(w, r, err)
			return
		}

		marshal.WriteJSON(w, r, res)
	}
}
