// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: cis.proto

package httppb

import (
	"net/http"

	"github.com/effective-security/porto/restserver"
	"github.com/effective-security/porto/xhttp/correlation"
	"github.com/effective-security/porto/xhttp/httperror"
	"github.com/effective-security/porto/xhttp/marshal"
	"github.com/effective-security/trustyca/api/pb"
)

// GetCISHTTPHandler handles HTTP requests for CIS service
func GetCISHTTPHandler(s pb.CISServer, withAccessCheck pb.CheckAccessFunc) restserver.Handle {
	return func(w http.ResponseWriter, r *http.Request, p restserver.Params) {
		action := r.URL.Path
		ctx := correlation.WithMetaFromRequest(r)

		var err error
		var res any

		req, _, err := pb.UnmarshalRequest(w, r)
		if err != nil {
			// UnmarshalRequest already writes error response
			return
		}

		if withAccessCheck != nil {
			err = withAccessCheck(ctx, req, action)
			if err != nil {
				marshal.WriteJSON(w, r, err)
				return
			}
		}

		switch action {

		case pb.CIS_GetRoots_FullMethodName:
			res, err = s.GetRoots(ctx, req.(*pb.ListRootsRequest))

		case pb.CIS_GetIssuer_FullMethodName:
			res, err = s.GetIssuer(ctx, req.(*pb.GetIssuerInfoRequest))

		case pb.CIS_GetCertificate_FullMethodName:
			res, err = s.GetCertificate(ctx, req.(*pb.GetCertificateInfoRequest))

		case pb.CIS_GetCertificateStatus_FullMethodName:
			res, err = s.GetCertificateStatus(ctx, req.(*pb.GetCertificateInfoRequest))

		case pb.CIS_GetCRL_FullMethodName:
			res, err = s.GetCRL(ctx, req.(*pb.GetCrlRequest))

		default:
			err = httperror.Malformed("invalid action: %s", action)
		}
		if err != nil {
			marshal.WriteJSON(w, r, err)
			return
		}

		marshal.WriteJSON(w, r, res)
	}
}
