// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: orgs.proto

package httppb

import (
	"net/http"

	"github.com/effective-security/porto/restserver"
	"github.com/effective-security/porto/xhttp/correlation"
	"github.com/effective-security/porto/xhttp/httperror"
	"github.com/effective-security/porto/xhttp/marshal"
	"github.com/effective-security/trustyca/api/pb"
	"google.golang.org/protobuf/types/known/emptypb"
)

// GetOrgsHTTPHandler handles HTTP requests for Orgs service
func GetOrgsHTTPHandler(s pb.OrgsServer, withAccessCheck pb.CheckAccessFunc) restserver.Handle {
	return func(w http.ResponseWriter, r *http.Request, p restserver.Params) {
		action := r.URL.Path
		ctx := correlation.WithMetaFromRequest(r)

		var err error
		var res any

		req, _, err := pb.UnmarshalRequest(w, r)
		if err != nil {
			// UnmarshalRequest already writes error response
			return
		}

		if withAccessCheck != nil {
			err = withAccessCheck(ctx, req, action)
			if err != nil {
				marshal.WriteJSON(w, r, err)
				return
			}
		}

		switch action {

		case pb.Orgs_RegisterOrg_FullMethodName:
			res, err = s.RegisterOrg(ctx, req.(*pb.RegisterOrgRequest))

		case pb.Orgs_UpdateOrg_FullMethodName:
			res, err = s.UpdateOrg(ctx, req.(*pb.UpdateOrgRequest))

		case pb.Orgs_GetOrg_FullMethodName:
			res, err = s.GetOrg(ctx, req.(*pb.GetOrgRequest))

		case pb.Orgs_DeleteOrg_FullMethodName:
			res, err = s.DeleteOrg(ctx, req.(*pb.DeleteOrgRequest))

		case pb.Orgs_GetUserMemberships_FullMethodName:
			res, err = s.GetUserMemberships(ctx, req.(*emptypb.Empty))

		case pb.Orgs_GetMembers_FullMethodName:
			res, err = s.GetMembers(ctx, req.(*pb.GetMembersRequest))

		case pb.Orgs_AddMember_FullMethodName:
			res, err = s.AddMember(ctx, req.(*pb.AddMemberRequest))

		case pb.Orgs_ChangeMemberRole_FullMethodName:
			res, err = s.ChangeMemberRole(ctx, req.(*pb.ChangeMemberRoleRequest))

		case pb.Orgs_DeleteMember_FullMethodName:
			res, err = s.DeleteMember(ctx, req.(*pb.DeleteMemberRequest))

		case pb.Orgs_DeleteInvite_FullMethodName:
			res, err = s.DeleteInvite(ctx, req.(*pb.DeleteInviteRequest))

		default:
			err = httperror.Malformed("invalid action: %s", action)
		}
		if err != nil {
			marshal.WriteJSON(w, r, err)
			return
		}

		marshal.WriteJSON(w, r, res)
	}
}
