// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: auth.proto

package pb

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

var JsonMarshalOptions = protojson.MarshalOptions{
	UseEnumNumbers:  true,
	EmitUnpopulated: false,
	UseProtoNames:   true,
	AllowPartial:    true,
}

var JsonUnmarshalOptions = protojson.UnmarshalOptions{
	AllowPartial:   true,
	DiscardUnknown: true,
}

// MarshalJSON implements json.Marshaler
func MarshalJSON(v any) ([]byte, error) {
	if JsonMarshalOptions.Multiline {
		return json.MarshalIndent(v, "", JsonMarshalOptions.Indent)
	}
	return json.Marshal(v)
}

// MarshalJSON implements json.Marshaler
func (msg *AuthProvidersRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *AuthProvidersRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *AuthProvidersResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *AuthProvidersResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UserInfo) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UserInfo) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *Token) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *Token) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UserTokenResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UserTokenResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *CallerStatusResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *CallerStatusResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *LoginInfo) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *LoginInfo) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ExchangeCodeRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ExchangeCodeRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *IDP) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *IDP) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *SelectOrgRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *SelectOrgRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *AllowedMethods) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *AllowedMethods) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ServiceAccessInfo) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ServiceAccessInfo) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *MethodAccess) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *MethodAccess) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *CallerScope) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *CallerScope) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}
