// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: ca.proto

package pb

// MarshalJSON implements json.Marshaler
func (msg *RegisterIssuerRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RegisterIssuerRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ImportIssuerRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ImportIssuerRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ActivateIssuerRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ActivateIssuerRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *GetIssuerRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *GetIssuerRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ListIssuersRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ListIssuersRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *IssuersResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *IssuersResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UpdateIssuerRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UpdateIssuerRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RegisterRootRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RegisterRootRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ListRootsRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ListRootsRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RootsResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RootsResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RegisterProfileRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RegisterProfileRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *GetProfileRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *GetProfileRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ListProfilesRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ListProfilesRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ProfilesResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ProfilesResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *DeleteProfileRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *DeleteProfileRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *SignCertificateRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *SignCertificateRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UpdateCertificateLabelRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UpdateCertificateLabelRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *GetCertificateRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *GetCertificateRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ListCertificatesRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ListCertificatesRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ListRevokedCertificatesRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ListRevokedCertificatesRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RevokeCertificateRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RevokeCertificateRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *CertificateResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *CertificateResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *CertificatesResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *CertificatesResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RevokedCertificateResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RevokedCertificateResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RevokedCertificatesResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RevokedCertificatesResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *GetCrlRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *GetCrlRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *PublishCrlsRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *PublishCrlsRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *CrlsResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *CrlsResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *CrlResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *CrlResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *OCSPRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *OCSPRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *OCSPResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *OCSPResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}
