// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: ca.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/effective-security/protoc-gen-go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterIssuerRequest specifies a request to create a new issuer
type RegisterIssuerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID of the owning project; empty for an org-wide issuer
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// Label of the issuer, unique per (Org, Project)
	Label string `protobuf:"bytes,3,opt,name=Label,proto3" json:"Label,omitempty"`
	// Type of the authority
	Type AuthorityType_Enum `protobuf:"varint,4,opt,name=Type,proto3,enum=pb.AuthorityType_Enum" json:"Type,omitempty"`
	// Subject of the issuer certificate
	Subject *X509Subject `protobuf:"bytes,5,opt,name=Subject,proto3" json:"Subject,omitempty"`
	// KeySpec of the key to generate; defaults to ECDSA P-256
	KeySpec *KeySpec `protobuf:"bytes,6,opt,name=KeySpec,proto3" json:"KeySpec,omitempty"`
	// KeyProvider selects the crypto provider; empty for the server default
	KeyProvider string `protobuf:"bytes,7,opt,name=KeyProvider,proto3" json:"KeyProvider,omitempty"`
	// ParentID specifies the signing issuer. It must belong to the same org,
	// or be a platform issuer that allows the Profile.
	// Empty for Root type, or to create a Pending issuer with a CSR.
	ParentID string `protobuf:"bytes,8,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	// Profile specifies the CA profile the parent uses to sign the issuer
	// certificate. Required when ParentID is set or Type is Root.
	Profile string `protobuf:"bytes,9,opt,name=Profile,proto3" json:"Profile,omitempty"`
	// Config provides runtime settings
	Config *IssuerConfig `protobuf:"bytes,10,opt,name=Config,proto3" json:"Config,omitempty"`
	// SAN specifies Subject Alternative Names for the issuer certificate
	SAN []string `protobuf:"bytes,11,rep,name=SAN,proto3" json:"SAN,omitempty"`
	// Extensions specifies additional extensions for the issuer certificate
	Extensions    []*X509Extension `protobuf:"bytes,12,rep,name=Extensions,proto3" json:"Extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterIssuerRequest) Reset() {
	*x = RegisterIssuerRequest{}
	mi := &file_ca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIssuerRequest) ProtoMessage() {}

func (x *RegisterIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIssuerRequest.ProtoReflect.Descriptor instead.
func (*RegisterIssuerRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterIssuerRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *RegisterIssuerRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *RegisterIssuerRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RegisterIssuerRequest) GetType() AuthorityType_Enum {
	if x != nil {
		return x.Type
	}
	return AuthorityType_Unknown
}

func (x *RegisterIssuerRequest) GetSubject() *X509Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *RegisterIssuerRequest) GetKeySpec() *KeySpec {
	if x != nil {
		return x.KeySpec
	}
	return nil
}

func (x *RegisterIssuerRequest) GetKeyProvider() string {
	if x != nil {
		return x.KeyProvider
	}
	return ""
}

func (x *RegisterIssuerRequest) GetParentID() string {
	if x != nil {
		return x.ParentID
	}
	return ""
}

func (x *RegisterIssuerRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *RegisterIssuerRequest) GetConfig() *IssuerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterIssuerRequest) GetSAN() []string {
	if x != nil {
		return x.SAN
	}
	return nil
}

func (x *RegisterIssuerRequest) GetExtensions() []*X509Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// ImportIssuerRequest specifies a request to import an existing issuer
type ImportIssuerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID of the owning project; empty for an org-wide issuer
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// Label of the issuer, unique per (Org, Project)
	Label string `protobuf:"bytes,3,opt,name=Label,proto3" json:"Label,omitempty"`
	// Type of the authority
	Type AuthorityType_Enum `protobuf:"varint,4,opt,name=Type,proto3,enum=pb.AuthorityType_Enum" json:"Type,omitempty"`
	// Certificate provides the issuer certificate in PEM format
	Certificate string `protobuf:"bytes,5,opt,name=Certificate,proto3" json:"Certificate,omitempty"`
	// Intermediates provides the intermediate CA certificates in PEM format
	Intermediates string `protobuf:"bytes,6,opt,name=Intermediates,proto3" json:"Intermediates,omitempty"`
	// Root provides the Root CA certificate in PEM format
	Root string `protobuf:"bytes,7,opt,name=Root,proto3" json:"Root,omitempty"`
	// KeyURI references an existing key in a crypto provider,
	// e.g. awskms://..., gcpkms://..., pkcs11:...
	KeyURI string `protobuf:"bytes,8,opt,name=KeyURI,proto3" json:"KeyURI,omitempty"`
	// KeyPem provides the private key in PEM format.
	// It is stored protected by the data protection provider.
	KeyPem string `protobuf:"bytes,9,opt,name=KeyPem,proto3" json:"KeyPem,omitempty"`
	// Config provides runtime settings
	Config        *IssuerConfig `protobuf:"bytes,10,opt,name=Config,proto3" json:"Config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportIssuerRequest) Reset() {
	*x = ImportIssuerRequest{}
	mi := &file_ca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportIssuerRequest) ProtoMessage() {}

func (x *ImportIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportIssuerRequest.ProtoReflect.Descriptor instead.
func (*ImportIssuerRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{1}
}

func (x *ImportIssuerRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *ImportIssuerRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *ImportIssuerRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ImportIssuerRequest) GetType() AuthorityType_Enum {
	if x != nil {
		return x.Type
	}
	return AuthorityType_Unknown
}

func (x *ImportIssuerRequest) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *ImportIssuerRequest) GetIntermediates() string {
	if x != nil {
		return x.Intermediates
	}
	return ""
}

func (x *ImportIssuerRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ImportIssuerRequest) GetKeyURI() string {
	if x != nil {
		return x.KeyURI
	}
	return ""
}

func (x *ImportIssuerRequest) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

func (x *ImportIssuerRequest) GetConfig() *IssuerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// ActivateIssuerRequest specifies the externally signed certificate for a
// Pending issuer
type ActivateIssuerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ID of the Pending issuer
	ID string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// Certificate provides the issuer certificate in PEM format
	Certificate string `protobuf:"bytes,3,opt,name=Certificate,proto3" json:"Certificate,omitempty"`
	// Intermediates provides the intermediate CA certificates in PEM format
	Intermediates string `protobuf:"bytes,4,opt,name=Intermediates,proto3" json:"Intermediates,omitempty"`
	// Root provides the Root CA certificate in PEM format
	Root          string `protobuf:"bytes,5,opt,name=Root,proto3" json:"Root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateIssuerRequest) Reset() {
	*x = ActivateIssuerRequest{}
	mi := &file_ca_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateIssuerRequest) ProtoMessage() {}

func (x *ActivateIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateIssuerRequest.ProtoReflect.Descriptor instead.
func (*ActivateIssuerRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{2}
}

func (x *ActivateIssuerRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *ActivateIssuerRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ActivateIssuerRequest) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *ActivateIssuerRequest) GetIntermediates() string {
	if x != nil {
		return x.Intermediates
	}
	return ""
}

func (x *ActivateIssuerRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

// GetIssuerRequest specifies an issuer by ID, label or IKID
type GetIssuerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID of the owning project; used with Label
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// ID of the issuer
	ID string `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	// Label of the issuer, resolved as (Org, Project) then (Org)
	Label string `protobuf:"bytes,4,opt,name=Label,proto3" json:"Label,omitempty"`
	// IKID specifies Issuer Key ID
	IKID          string `protobuf:"bytes,5,opt,name=IKID,proto3" json:"IKID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssuerRequest) Reset() {
	*x = GetIssuerRequest{}
	mi := &file_ca_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssuerRequest) ProtoMessage() {}

func (x *GetIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssuerRequest.ProtoReflect.Descriptor instead.
func (*GetIssuerRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{3}
}

func (x *GetIssuerRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *GetIssuerRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *GetIssuerRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetIssuerRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GetIssuerRequest) GetIKID() string {
	if x != nil {
		return x.IKID
	}
	return ""
}

// ListIssuersRequest specifies a paginated list of issuers
type ListIssuersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID filters by project; empty returns org-wide and all project
	// issuers
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// Status filters by status; Unknown returns all
	Status IssuerStatus_Enum `protobuf:"varint,3,opt,name=Status,proto3,enum=pb.IssuerStatus_Enum" json:"Status,omitempty"`
	// Type filters by authority type; Unknown returns all
	Type AuthorityType_Enum `protobuf:"varint,4,opt,name=Type,proto3,enum=pb.AuthorityType_Enum" json:"Type,omitempty"`
	// Limit specifies maximum number of records to return
	Limit uint32 `protobuf:"varint,5,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// Offset specifies offset for the offset-based pagination
	Offset uint32 `protobuf:"varint,6,opt,name=Offset,proto3" json:"Offset,omitempty"`
	// Cursor specifies cursor for the cursor-based pagination.
	// Use "initial" to start the pagination or pass the cursor returned from
	// the previous request.
	Cursor        string `protobuf:"bytes,7,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIssuersRequest) Reset() {
	*x = ListIssuersRequest{}
	mi := &file_ca_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIssuersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIssuersRequest) ProtoMessage() {}

func (x *ListIssuersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIssuersRequest.ProtoReflect.Descriptor instead.
func (*ListIssuersRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{4}
}

func (x *ListIssuersRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *ListIssuersRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *ListIssuersRequest) GetStatus() IssuerStatus_Enum {
	if x != nil {
		return x.Status
	}
	return IssuerStatus_Unknown
}

func (x *ListIssuersRequest) GetType() AuthorityType_Enum {
	if x != nil {
		return x.Type
	}
	return AuthorityType_Unknown
}

func (x *ListIssuersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListIssuersRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListIssuersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// IssuersResponse returns list of issuers
type IssuersResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Issuers []*Issuer              `protobuf:"bytes,1,rep,name=Issuers,proto3" json:"Issuers,omitempty"`
	// NextPage specifies pagination information, if there are more pages to
	// fetch. If there are no more pages to fetch, NextPage will be empty.
	NextPage      *NextPage `protobuf:"bytes,2,opt,name=NextPage,proto3" json:"NextPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuersResponse) Reset() {
	*x = IssuersResponse{}
	mi := &file_ca_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuersResponse) ProtoMessage() {}

func (x *IssuersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuersResponse.ProtoReflect.Descriptor instead.
func (*IssuersResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{5}
}

func (x *IssuersResponse) GetIssuers() []*Issuer {
	if x != nil {
		return x.Issuers
	}
	return nil
}

func (x *IssuersResponse) GetNextPage() *NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

// UpdateIssuerRequest updates issuer config or status
type UpdateIssuerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ID of the issuer
	ID string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// Config replaces runtime settings when provided
	Config *IssuerConfig `protobuf:"bytes,3,opt,name=Config,proto3" json:"Config,omitempty"`
	// Status changes the status when provided: Archived or Destroyed
	Status        IssuerStatus_Enum `protobuf:"varint,4,opt,name=Status,proto3,enum=pb.IssuerStatus_Enum" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssuerRequest) Reset() {
	*x = UpdateIssuerRequest{}
	mi := &file_ca_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssuerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssuerRequest) ProtoMessage() {}

func (x *UpdateIssuerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssuerRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssuerRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateIssuerRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *UpdateIssuerRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateIssuerRequest) GetConfig() *IssuerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateIssuerRequest) GetStatus() IssuerStatus_Enum {
	if x != nil {
		return x.Status
	}
	return IssuerStatus_Unknown
}

// RegisterRootRequest registers an external trust anchor
type RegisterRootRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// Pem encoded root certificate
	Pem string `protobuf:"bytes,2,opt,name=Pem,proto3" json:"Pem,omitempty"`
	// Trust scope
	Trust         Trust_Enum `protobuf:"varint,3,opt,name=Trust,proto3,enum=pb.Trust_Enum" json:"Trust,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRootRequest) Reset() {
	*x = RegisterRootRequest{}
	mi := &file_ca_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRootRequest) ProtoMessage() {}

func (x *RegisterRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRootRequest.ProtoReflect.Descriptor instead.
func (*RegisterRootRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRootRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *RegisterRootRequest) GetPem() string {
	if x != nil {
		return x.Pem
	}
	return ""
}

func (x *RegisterRootRequest) GetTrust() Trust_Enum {
	if x != nil {
		return x.Trust
	}
	return Trust_Any
}

// ListRootsRequest specifies a list of trust anchors
type ListRootsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org; empty for platform roots
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// Limit specifies maximum number of records to return
	Limit uint32 `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// Offset specifies offset for the offset-based pagination
	Offset uint32 `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	// Cursor specifies cursor for the cursor-based pagination
	Cursor        string `protobuf:"bytes,4,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRootsRequest) Reset() {
	*x = ListRootsRequest{}
	mi := &file_ca_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRootsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRootsRequest) ProtoMessage() {}

func (x *ListRootsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRootsRequest.ProtoReflect.Descriptor instead.
func (*ListRootsRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{8}
}

func (x *ListRootsRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *ListRootsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRootsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRootsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// RootsResponse returns Root Certificates
type RootsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Roots []*RootCertificate     `protobuf:"bytes,1,rep,name=Roots,proto3" json:"Roots,omitempty"`
	// NextPage specifies pagination information, if there are more pages to
	// fetch. If there are no more pages to fetch, NextPage will be empty.
	NextPage      *NextPage `protobuf:"bytes,2,opt,name=NextPage,proto3" json:"NextPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootsResponse) Reset() {
	*x = RootsResponse{}
	mi := &file_ca_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootsResponse) ProtoMessage() {}

func (x *RootsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootsResponse.ProtoReflect.Descriptor instead.
func (*RootsResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{9}
}

func (x *RootsResponse) GetRoots() []*RootCertificate {
	if x != nil {
		return x.Roots
	}
	return nil
}

func (x *RootsResponse) GetNextPage() *NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

// RegisterProfileRequest creates or replaces a profile
type RegisterProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID of the owning project; empty for an org-wide profile
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// Profile provides the profile definition.
	// Profile.Label and Profile.IssuerLabel are required.
	Profile       *CertProfile `protobuf:"bytes,3,opt,name=Profile,proto3" json:"Profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProfileRequest) Reset() {
	*x = RegisterProfileRequest{}
	mi := &file_ca_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProfileRequest) ProtoMessage() {}

func (x *RegisterProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProfileRequest.ProtoReflect.Descriptor instead.
func (*RegisterProfileRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterProfileRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *RegisterProfileRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *RegisterProfileRequest) GetProfile() *CertProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetProfileRequest specifies a profile by ID or label
type GetProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID of the owning project; used with Label
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// ID of the profile
	ID string `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	// Label of the profile, resolved as (Org, Project) then (Org)
	Label         string `protobuf:"bytes,4,opt,name=Label,proto3" json:"Label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_ca_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{11}
}

func (x *GetProfileRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *GetProfileRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *GetProfileRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetProfileRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// ListProfilesRequest specifies a paginated list of profiles
type ListProfilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID filters by project; empty returns org-wide and all project
	// profiles
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// IssuerLabel filters by issuer label
	IssuerLabel string `protobuf:"bytes,3,opt,name=IssuerLabel,proto3" json:"IssuerLabel,omitempty"`
	// Limit specifies maximum number of records to return
	Limit uint32 `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// Offset specifies offset for the offset-based pagination
	Offset uint32 `protobuf:"varint,5,opt,name=Offset,proto3" json:"Offset,omitempty"`
	// Cursor specifies cursor for the cursor-based pagination
	Cursor        string `protobuf:"bytes,6,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_ca_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{12}
}

func (x *ListProfilesRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *ListProfilesRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *ListProfilesRequest) GetIssuerLabel() string {
	if x != nil {
		return x.IssuerLabel
	}
	return ""
}

func (x *ListProfilesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProfilesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProfilesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ProfilesResponse returns list of profiles
type ProfilesResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Profiles []*CertProfile         `protobuf:"bytes,1,rep,name=Profiles,proto3" json:"Profiles,omitempty"`
	// NextPage specifies pagination information, if there are more pages to
	// fetch. If there are no more pages to fetch, NextPage will be empty.
	NextPage      *NextPage `protobuf:"bytes,2,opt,name=NextPage,proto3" json:"NextPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesResponse) Reset() {
	*x = ProfilesResponse{}
	mi := &file_ca_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesResponse) ProtoMessage() {}

func (x *ProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesResponse.ProtoReflect.Descriptor instead.
func (*ProfilesResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{13}
}

func (x *ProfilesResponse) GetProfiles() []*CertProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ProfilesResponse) GetNextPage() *NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

// DeleteProfileRequest deletes a profile
type DeleteProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ID of the profile
	ID            string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_ca_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteProfileRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *DeleteProfileRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// SignCertificateRequest specifies certificate sign request
type SignCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID of the owning project; recorded on the certificate and used to
	// resolve project-scoped profiles and issuers
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// Profile specifies the certificate profile label
	Profile string `protobuf:"bytes,3,opt,name=Profile,proto3" json:"Profile,omitempty"`
	// IssuerLabel selects the issuer when the profile binds to "*";
	// otherwise it must match the profile's issuer
	IssuerLabel string `protobuf:"bytes,4,opt,name=IssuerLabel,proto3" json:"IssuerLabel,omitempty"`
	// RequestFormat provides the certificate request format: PEM or DER
	RequestFormat EncodingFormat_Enum `protobuf:"varint,5,opt,name=RequestFormat,proto3,enum=pb.EncodingFormat_Enum" json:"RequestFormat,omitempty"`
	// Request provides the PKCS#10 certificate request
	Request []byte `protobuf:"bytes,6,opt,name=Request,proto3" json:"Request,omitempty"`
	// SAN specifies Subject Alternative Names to add or override
	SAN []string `protobuf:"bytes,7,rep,name=SAN,proto3" json:"SAN,omitempty"`
	// Subject overrides the subject name from the request
	Subject *X509Subject `protobuf:"bytes,8,opt,name=Subject,proto3" json:"Subject,omitempty"`
	// NotBefore overrides the validity start in RFC3339 format;
	// no backdate is applied when provided
	NotBefore string `protobuf:"bytes,9,opt,name=NotBefore,proto3" json:"NotBefore,omitempty"`
	// NotAfter overrides the validity end in RFC3339 format;
	// it must not exceed the profile expiry
	NotAfter string `protobuf:"bytes,10,opt,name=NotAfter,proto3" json:"NotAfter,omitempty"`
	// Extensions specifies additional extensions to include, subject to the
	// profile's AllowedExtensions
	Extensions []*X509Extension `protobuf:"bytes,11,rep,name=Extensions,proto3" json:"Extensions,omitempty"`
	// Label is provided by the client for search and display
	Label string `protobuf:"bytes,12,opt,name=Label,proto3" json:"Label,omitempty"`
	// Metadata is provided by the client
	Metadata      map[string]string `protobuf:"bytes,13,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignCertificateRequest) Reset() {
	*x = SignCertificateRequest{}
	mi := &file_ca_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCertificateRequest) ProtoMessage() {}

func (x *SignCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCertificateRequest.ProtoReflect.Descriptor instead.
func (*SignCertificateRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{15}
}

func (x *SignCertificateRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *SignCertificateRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *SignCertificateRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SignCertificateRequest) GetIssuerLabel() string {
	if x != nil {
		return x.IssuerLabel
	}
	return ""
}

func (x *SignCertificateRequest) GetRequestFormat() EncodingFormat_Enum {
	if x != nil {
		return x.RequestFormat
	}
	return EncodingFormat_PEM
}

func (x *SignCertificateRequest) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SignCertificateRequest) GetSAN() []string {
	if x != nil {
		return x.SAN
	}
	return nil
}

func (x *SignCertificateRequest) GetSubject() *X509Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *SignCertificateRequest) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *SignCertificateRequest) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *SignCertificateRequest) GetExtensions() []*X509Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *SignCertificateRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SignCertificateRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpdateCertificateLabelRequest specifies certificate label update request
type UpdateCertificateLabelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ID specifies certificate ID
	ID string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// Label is provided by the client
	Label string `protobuf:"bytes,3,opt,name=Label,proto3" json:"Label,omitempty"`
	// Metadata replaces the client metadata when provided
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=Metadata,proto3" json:"Metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCertificateLabelRequest) Reset() {
	*x = UpdateCertificateLabelRequest{}
	mi := &file_ca_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCertificateLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCertificateLabelRequest) ProtoMessage() {}

func (x *UpdateCertificateLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCertificateLabelRequest.ProtoReflect.Descriptor instead.
func (*UpdateCertificateLabelRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCertificateLabelRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *UpdateCertificateLabelRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateCertificateLabelRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateCertificateLabelRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GetCertificateRequest specifies certificate by ID, SKID, Sha256 or issuer
// and serial number
type GetCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ID specifies certificate ID
	ID string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// SKID specifies Subject Key ID to search
	SKID string `protobuf:"bytes,3,opt,name=SKID,proto3" json:"SKID,omitempty"`
	// Sha256 specifies the certificate thumbprint to search
	Sha256 string `protobuf:"bytes,4,opt,name=Sha256,proto3" json:"Sha256,omitempty"`
	// IssuerSerial specifies Issuer Key ID and certificate serial number
	IssuerSerial  *IssuerSerial `protobuf:"bytes,5,opt,name=IssuerSerial,proto3" json:"IssuerSerial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	mi := &file_ca_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{17}
}

func (x *GetCertificateRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *GetCertificateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetCertificateRequest) GetSKID() string {
	if x != nil {
		return x.SKID
	}
	return ""
}

func (x *GetCertificateRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *GetCertificateRequest) GetIssuerSerial() *IssuerSerial {
	if x != nil {
		return x.IssuerSerial
	}
	return nil
}

// ListCertificatesRequest specifies a paginated list of certificates,
// sorted by ID descending (newest first)
type ListCertificatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID filters by project; empty returns org-wide and all project
	// certificates
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// IKID filters by issuer
	IKID string `protobuf:"bytes,3,opt,name=IKID,proto3" json:"IKID,omitempty"`
	// Profile filters by profile label
	Profile string `protobuf:"bytes,4,opt,name=Profile,proto3" json:"Profile,omitempty"`
	// Status filters by status; Unknown returns all
	Status CertificateStatus_Enum `protobuf:"varint,5,opt,name=Status,proto3,enum=pb.CertificateStatus_Enum" json:"Status,omitempty"`
	// ExpiringBefore filters certificates with NotAfter before the time,
	// in RFC3339 format
	ExpiringBefore string `protobuf:"bytes,6,opt,name=ExpiringBefore,proto3" json:"ExpiringBefore,omitempty"`
	// Limit specifies maximum number of records to return
	Limit uint32 `protobuf:"varint,7,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// Offset specifies offset for the offset-based pagination
	Offset uint32 `protobuf:"varint,8,opt,name=Offset,proto3" json:"Offset,omitempty"`
	// Cursor specifies cursor for the cursor-based pagination.
	// Use "initial" to start the pagination or pass the cursor returned from
	// the previous request.
	Cursor        string `protobuf:"bytes,9,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCertificatesRequest) Reset() {
	*x = ListCertificatesRequest{}
	mi := &file_ca_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertificatesRequest) ProtoMessage() {}

func (x *ListCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertificatesRequest.ProtoReflect.Descriptor instead.
func (*ListCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{18}
}

func (x *ListCertificatesRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *ListCertificatesRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *ListCertificatesRequest) GetIKID() string {
	if x != nil {
		return x.IKID
	}
	return ""
}

func (x *ListCertificatesRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ListCertificatesRequest) GetStatus() CertificateStatus_Enum {
	if x != nil {
		return x.Status
	}
	return CertificateStatus_Unknown
}

func (x *ListCertificatesRequest) GetExpiringBefore() string {
	if x != nil {
		return x.ExpiringBefore
	}
	return ""
}

func (x *ListCertificatesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCertificatesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCertificatesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ListRevokedCertificatesRequest specifies a paginated list of revoked
// certificates, sorted by revocation ID descending
type ListRevokedCertificatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ProjectID filters by project
	ProjectID string `protobuf:"bytes,2,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	// IKID filters by issuer
	IKID string `protobuf:"bytes,3,opt,name=IKID,proto3" json:"IKID,omitempty"`
	// Limit specifies maximum number of records to return
	Limit uint32 `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	// Offset specifies offset for the offset-based pagination
	Offset uint32 `protobuf:"varint,5,opt,name=Offset,proto3" json:"Offset,omitempty"`
	// Cursor specifies cursor for the cursor-based pagination
	Cursor        string `protobuf:"bytes,6,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRevokedCertificatesRequest) Reset() {
	*x = ListRevokedCertificatesRequest{}
	mi := &file_ca_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevokedCertificatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevokedCertificatesRequest) ProtoMessage() {}

func (x *ListRevokedCertificatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevokedCertificatesRequest.ProtoReflect.Descriptor instead.
func (*ListRevokedCertificatesRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{19}
}

func (x *ListRevokedCertificatesRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *ListRevokedCertificatesRequest) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

func (x *ListRevokedCertificatesRequest) GetIKID() string {
	if x != nil {
		return x.IKID
	}
	return ""
}

func (x *ListRevokedCertificatesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRevokedCertificatesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRevokedCertificatesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// RevokeCertificateRequest specifies revocation request
type RevokeCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// ID specifies certificate ID
	ID string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// SKID specifies Subject Key ID to search
	SKID string `protobuf:"bytes,3,opt,name=SKID,proto3" json:"SKID,omitempty"`
	// IssuerSerial specifies Issuer Key ID and certificate serial number
	IssuerSerial *IssuerSerial `protobuf:"bytes,4,opt,name=IssuerSerial,proto3" json:"IssuerSerial,omitempty"`
	// Reason for revocation
	Reason ReasonCode_Enum `protobuf:"varint,5,opt,name=Reason,proto3,enum=pb.ReasonCode_Enum" json:"Reason,omitempty"`
	// ReasonText provides optional free-form revocation note
	ReasonText    string `protobuf:"bytes,6,opt,name=ReasonText,proto3" json:"ReasonText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertificateRequest) Reset() {
	*x = RevokeCertificateRequest{}
	mi := &file_ca_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertificateRequest) ProtoMessage() {}

func (x *RevokeCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertificateRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertificateRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{20}
}

func (x *RevokeCertificateRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *RevokeCertificateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RevokeCertificateRequest) GetSKID() string {
	if x != nil {
		return x.SKID
	}
	return ""
}

func (x *RevokeCertificateRequest) GetIssuerSerial() *IssuerSerial {
	if x != nil {
		return x.IssuerSerial
	}
	return nil
}

func (x *RevokeCertificateRequest) GetReason() ReasonCode_Enum {
	if x != nil {
		return x.Reason
	}
	return ReasonCode_Unspecified
}

func (x *RevokeCertificateRequest) GetReasonText() string {
	if x != nil {
		return x.ReasonText
	}
	return ""
}

// CertificateResponse returns Certificate
type CertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   *Certificate           `protobuf:"bytes,1,opt,name=Certificate,proto3" json:"Certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_ca_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{21}
}

func (x *CertificateResponse) GetCertificate() *Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

// CertificatesResponse returns Certificates list
type CertificatesResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Certificates []*Certificate         `protobuf:"bytes,1,rep,name=Certificates,proto3" json:"Certificates,omitempty"`
	// NextPage specifies pagination information, if there are more pages to
	// fetch. If there are no more pages to fetch, NextPage will be empty.
	NextPage      *NextPage `protobuf:"bytes,2,opt,name=NextPage,proto3" json:"NextPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificatesResponse) Reset() {
	*x = CertificatesResponse{}
	mi := &file_ca_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificatesResponse) ProtoMessage() {}

func (x *CertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificatesResponse.ProtoReflect.Descriptor instead.
func (*CertificatesResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{22}
}

func (x *CertificatesResponse) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *CertificatesResponse) GetNextPage() *NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

// RevokedCertificateResponse returns Revoked Certificate
type RevokedCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       *RevokedCertificate    `protobuf:"bytes,1,opt,name=Revoked,proto3" json:"Revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokedCertificateResponse) Reset() {
	*x = RevokedCertificateResponse{}
	mi := &file_ca_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokedCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokedCertificateResponse) ProtoMessage() {}

func (x *RevokedCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokedCertificateResponse.ProtoReflect.Descriptor instead.
func (*RevokedCertificateResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{23}
}

func (x *RevokedCertificateResponse) GetRevoked() *RevokedCertificate {
	if x != nil {
		return x.Revoked
	}
	return nil
}

// RevokedCertificatesResponse returns Revoked Certificates list
type RevokedCertificatesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RevokedCertificates []*RevokedCertificate  `protobuf:"bytes,1,rep,name=RevokedCertificates,proto3" json:"RevokedCertificates,omitempty"`
	// NextPage specifies pagination information, if there are more pages to
	// fetch. If there are no more pages to fetch, NextPage will be empty.
	NextPage      *NextPage `protobuf:"bytes,2,opt,name=NextPage,proto3" json:"NextPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokedCertificatesResponse) Reset() {
	*x = RevokedCertificatesResponse{}
	mi := &file_ca_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokedCertificatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokedCertificatesResponse) ProtoMessage() {}

func (x *RevokedCertificatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokedCertificatesResponse.ProtoReflect.Descriptor instead.
func (*RevokedCertificatesResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{24}
}

func (x *RevokedCertificatesResponse) GetRevokedCertificates() []*RevokedCertificate {
	if x != nil {
		return x.RevokedCertificates
	}
	return nil
}

func (x *RevokedCertificatesResponse) GetNextPage() *NextPage {
	if x != nil {
		return x.NextPage
	}
	return nil
}

// GetCrlRequest specifies CRL request by IKID
type GetCrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org; empty allows lookup across orgs for CIS
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// IKID specifies Issuer Key ID
	IKID          string `protobuf:"bytes,2,opt,name=IKID,proto3" json:"IKID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCrlRequest) Reset() {
	*x = GetCrlRequest{}
	mi := &file_ca_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrlRequest) ProtoMessage() {}

func (x *GetCrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrlRequest.ProtoReflect.Descriptor instead.
func (*GetCrlRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{25}
}

func (x *GetCrlRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *GetCrlRequest) GetIKID() string {
	if x != nil {
		return x.IKID
	}
	return ""
}

// PublishCrlsRequest allows to publish CRLs on demand
type PublishCrlsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OrgID of the owning org; empty for all orgs
	OrgID string `protobuf:"bytes,1,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	// IKID specifies Issuer Key ID; empty to publish for all issuers in scope
	IKID string `protobuf:"bytes,2,opt,name=IKID,proto3" json:"IKID,omitempty"`
	// Force specifies to publish even if the current CRL is not due for renewal
	Force         bool `protobuf:"varint,3,opt,name=Force,proto3" json:"Force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCrlsRequest) Reset() {
	*x = PublishCrlsRequest{}
	mi := &file_ca_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCrlsRequest) ProtoMessage() {}

func (x *PublishCrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCrlsRequest.ProtoReflect.Descriptor instead.
func (*PublishCrlsRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{26}
}

func (x *PublishCrlsRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *PublishCrlsRequest) GetIKID() string {
	if x != nil {
		return x.IKID
	}
	return ""
}

func (x *PublishCrlsRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// CrlsResponse returns published CRLs
type CrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crls          []*Crl                 `protobuf:"bytes,1,rep,name=Crls,proto3" json:"Crls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrlsResponse) Reset() {
	*x = CrlsResponse{}
	mi := &file_ca_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrlsResponse) ProtoMessage() {}

func (x *CrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrlsResponse.ProtoReflect.Descriptor instead.
func (*CrlsResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{27}
}

func (x *CrlsResponse) GetCrls() []*Crl {
	if x != nil {
		return x.Crls
	}
	return nil
}

// CrlResponse returns CRL
type CrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crl           *Crl                   `protobuf:"bytes,1,opt,name=Crl,proto3" json:"Crl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrlResponse) Reset() {
	*x = CrlResponse{}
	mi := &file_ca_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrlResponse) ProtoMessage() {}

func (x *CrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrlResponse.ProtoReflect.Descriptor instead.
func (*CrlResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{28}
}

func (x *CrlResponse) GetCrl() *Crl {
	if x != nil {
		return x.Crl
	}
	return nil
}

// OCSPRequest provides DER encoded OCSP request
type OCSPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Der provides DER encoded request
	Der           []byte `protobuf:"bytes,1,opt,name=Der,proto3" json:"Der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCSPRequest) Reset() {
	*x = OCSPRequest{}
	mi := &file_ca_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCSPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCSPRequest) ProtoMessage() {}

func (x *OCSPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCSPRequest.ProtoReflect.Descriptor instead.
func (*OCSPRequest) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{29}
}

func (x *OCSPRequest) GetDer() []byte {
	if x != nil {
		return x.Der
	}
	return nil
}

// OCSPResponse returns DER encoded OCSP response
type OCSPResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Der provides DER encoded response
	Der           []byte `protobuf:"bytes,1,opt,name=Der,proto3" json:"Der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCSPResponse) Reset() {
	*x = OCSPResponse{}
	mi := &file_ca_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCSPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCSPResponse) ProtoMessage() {}

func (x *OCSPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ca_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCSPResponse.ProtoReflect.Descriptor instead.
func (*OCSPResponse) Descriptor() ([]byte, []int) {
	return file_ca_proto_rawDescGZIP(), []int{30}
}

func (x *OCSPResponse) GetDer() []byte {
	if x != nil {
		return x.Der
	}
	return nil
}

var File_ca_proto protoreflect.FileDescriptor

const file_ca_proto_rawDesc = "" +
	"\n" +
	"\bca.proto\x12\x02pb\x1a\x18es/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\vtypes.proto\x1a\n" +
	"pkix.proto\"\xc2\x03\n" +
	"\x15RegisterIssuerRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12\x1e\n" +
	"\x05Label\x18\x03 \x01(\tB\b\xe8\xf3\x18\x01\x80\xf4\x18@R\x05Label\x120\n" +
	"\x04Type\x18\x04 \x01(\x0e2\x16.pb.AuthorityType.EnumB\x04\xe8\xf3\x18\x01R\x04Type\x12/\n" +
	"\aSubject\x18\x05 \x01(\v2\x0f.pb.X509SubjectB\x04\xe8\xf3\x18\x01R\aSubject\x12%\n" +
	"\aKeySpec\x18\x06 \x01(\v2\v.pb.KeySpecR\aKeySpec\x12 \n" +
	"\vKeyProvider\x18\a \x01(\tR\vKeyProvider\x12\x1a\n" +
	"\bParentID\x18\b \x01(\tR\bParentID\x12\x18\n" +
	"\aProfile\x18\t \x01(\tR\aProfile\x12(\n" +
	"\x06Config\x18\n" +
	" \x01(\v2\x10.pb.IssuerConfigR\x06Config\x12\x10\n" +
	"\x03SAN\x18\v \x03(\tR\x03SAN\x121\n" +
	"\n" +
	"Extensions\x18\f \x03(\v2\x11.pb.X509ExtensionR\n" +
	"Extensions\"\xf5\x02\n" +
	"\x13ImportIssuerRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12\x1e\n" +
	"\x05Label\x18\x03 \x01(\tB\b\xe8\xf3\x18\x01\x80\xf4\x18@R\x05Label\x120\n" +
	"\x04Type\x18\x04 \x01(\x0e2\x16.pb.AuthorityType.EnumB\x04\xe8\xf3\x18\x01R\x04Type\x12&\n" +
	"\vCertificate\x18\x05 \x01(\tB\x04\xe8\xf3\x18\x01R\vCertificate\x12$\n" +
	"\rIntermediates\x18\x06 \x01(\tR\rIntermediates\x12\x12\n" +
	"\x04Root\x18\a \x01(\tR\x04Root\x12\"\n" +
	"\x06KeyURI\x18\b \x01(\tB\n" +
	"\xf2\xf3\x18\x06KeyPemR\x06KeyURI\x12\"\n" +
	"\x06KeyPem\x18\t \x01(\tB\n" +
	"\xf2\xf3\x18\x06KeyURIR\x06KeyPem\x12(\n" +
	"\x06Config\x18\n" +
	" \x01(\v2\x10.pb.IssuerConfigR\x06Config\"\xab\x01\n" +
	"\x15ActivateIssuerRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x14\n" +
	"\x02ID\x18\x02 \x01(\tB\x04\xe8\xf3\x18\x01R\x02ID\x12&\n" +
	"\vCertificate\x18\x03 \x01(\tB\x04\xe8\xf3\x18\x01R\vCertificate\x12$\n" +
	"\rIntermediates\x18\x04 \x01(\tR\rIntermediates\x12\x12\n" +
	"\x04Root\x18\x05 \x01(\tR\x04Root\"\xb1\x01\n" +
	"\x10GetIssuerRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12\x1e\n" +
	"\x02ID\x18\x03 \x01(\tB\x0e\xf2\xf3\x18\n" +
	"Label,IKIDR\x02ID\x12!\n" +
	"\x05Label\x18\x04 \x01(\tB\v\xf2\xf3\x18\aID,IKIDR\x05Label\x12 \n" +
	"\x04IKID\x18\x05 \x01(\tB\f\xf2\xf3\x18\bID,LabelR\x04IKID\"\xef\x01\n" +
	"\x12ListIssuersRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12-\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x15.pb.IssuerStatus.EnumR\x06Status\x12*\n" +
	"\x04Type\x18\x04 \x01(\x0e2\x16.pb.AuthorityType.EnumR\x04Type\x12\x14\n" +
	"\x05Limit\x18\x05 \x01(\rR\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x06 \x01(\rR\x06Offset\x12\x16\n" +
	"\x06Cursor\x18\a \x01(\tR\x06Cursor\"a\n" +
	"\x0fIssuersResponse\x12$\n" +
	"\aIssuers\x18\x01 \x03(\v2\n" +
	".pb.IssuerR\aIssuers\x12(\n" +
	"\bNextPage\x18\x02 \x01(\v2\f.pb.NextPageR\bNextPage\"\xa0\x01\n" +
	"\x13UpdateIssuerRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x14\n" +
	"\x02ID\x18\x02 \x01(\tB\x04\xe8\xf3\x18\x01R\x02ID\x12(\n" +
	"\x06Config\x18\x03 \x01(\v2\x10.pb.IssuerConfigR\x06Config\x12-\n" +
	"\x06Status\x18\x04 \x01(\x0e2\x15.pb.IssuerStatus.EnumR\x06Status\"o\n" +
	"\x13RegisterRootRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x16\n" +
	"\x03Pem\x18\x02 \x01(\tB\x04\xe8\xf3\x18\x01R\x03Pem\x12$\n" +
	"\x05Trust\x18\x03 \x01(\x0e2\x0e.pb.Trust.EnumR\x05Trust\"n\n" +
	"\x10ListRootsRequest\x12\x14\n" +
	"\x05OrgID\x18\x01 \x01(\tR\x05OrgID\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\rR\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x03 \x01(\rR\x06Offset\x12\x16\n" +
	"\x06Cursor\x18\x04 \x01(\tR\x06Cursor\"d\n" +
	"\rRootsResponse\x12)\n" +
	"\x05Roots\x18\x01 \x03(\v2\x13.pb.RootCertificateR\x05Roots\x12(\n" +
	"\bNextPage\x18\x02 \x01(\v2\f.pb.NextPageR\bNextPage\"\x83\x01\n" +
	"\x16RegisterProfileRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12/\n" +
	"\aProfile\x18\x03 \x01(\v2\x0f.pb.CertProfileB\x04\xe8\xf3\x18\x01R\aProfile\"\x86\x01\n" +
	"\x11GetProfileRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12\x19\n" +
	"\x02ID\x18\x03 \x01(\tB\t\xf2\xf3\x18\x05LabelR\x02ID\x12\x1c\n" +
	"\x05Label\x18\x04 \x01(\tB\x06\xf2\xf3\x18\x02IDR\x05Label\"\xb7\x01\n" +
	"\x13ListProfilesRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12 \n" +
	"\vIssuerLabel\x18\x03 \x01(\tR\vIssuerLabel\x12\x14\n" +
	"\x05Limit\x18\x04 \x01(\rR\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x05 \x01(\rR\x06Offset\x12\x16\n" +
	"\x06Cursor\x18\x06 \x01(\tR\x06Cursor\"i\n" +
	"\x10ProfilesResponse\x12+\n" +
	"\bProfiles\x18\x01 \x03(\v2\x0f.pb.CertProfileR\bProfiles\x12(\n" +
	"\bNextPage\x18\x02 \x01(\v2\f.pb.NextPageR\bNextPage\"H\n" +
	"\x14DeleteProfileRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x14\n" +
	"\x02ID\x18\x02 \x01(\tB\x04\xe8\xf3\x18\x01R\x02ID\"\xbd\x04\n" +
	"\x16SignCertificateRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12\x1e\n" +
	"\aProfile\x18\x03 \x01(\tB\x04\xe8\xf3\x18\x01R\aProfile\x12 \n" +
	"\vIssuerLabel\x18\x04 \x01(\tR\vIssuerLabel\x12=\n" +
	"\rRequestFormat\x18\x05 \x01(\x0e2\x17.pb.EncodingFormat.EnumR\rRequestFormat\x12\x1e\n" +
	"\aRequest\x18\x06 \x01(\fB\x04\xe8\xf3\x18\x01R\aRequest\x12\x10\n" +
	"\x03SAN\x18\a \x03(\tR\x03SAN\x12)\n" +
	"\aSubject\x18\b \x01(\v2\x0f.pb.X509SubjectR\aSubject\x12\x1c\n" +
	"\tNotBefore\x18\t \x01(\tR\tNotBefore\x12\x1a\n" +
	"\bNotAfter\x18\n" +
	" \x01(\tR\bNotAfter\x121\n" +
	"\n" +
	"Extensions\x18\v \x03(\v2\x11.pb.X509ExtensionR\n" +
	"Extensions\x12\x1b\n" +
	"\x05Label\x18\f \x01(\tB\x05\x80\xf4\x18\x84\x02R\x05Label\x12D\n" +
	"\bMetadata\x18\r \x03(\v2(.pb.SignCertificateRequest.MetadataEntryR\bMetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\x1dUpdateCertificateLabelRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x14\n" +
	"\x02ID\x18\x02 \x01(\tB\x04\xe8\xf3\x18\x01R\x02ID\x12\x1b\n" +
	"\x05Label\x18\x03 \x01(\tB\x05\x80\xf4\x18\x84\x02R\x05Label\x12K\n" +
	"\bMetadata\x18\x04 \x03(\v2/.pb.UpdateCertificateLabelRequest.MetadataEntryR\bMetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x15GetCertificateRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12,\n" +
	"\x02ID\x18\x02 \x01(\tB\x1c\xf2\xf3\x18\x18SKID,Sha256,IssuerSerialR\x02ID\x12.\n" +
	"\x04SKID\x18\x03 \x01(\tB\x1a\xf2\xf3\x18\x16ID,Sha256,IssuerSerialR\x04SKID\x120\n" +
	"\x06Sha256\x18\x04 \x01(\tB\x18\xf2\xf3\x18\x14ID,SKID,IssuerSerialR\x06Sha256\x12H\n" +
	"\fIssuerSerial\x18\x05 \x01(\v2\x10.pb.IssuerSerialB\x12\xf2\xf3\x18\x0eID,SKID,Sha256R\fIssuerSerial\"\xa3\x02\n" +
	"\x17ListCertificatesRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12\x12\n" +
	"\x04IKID\x18\x03 \x01(\tR\x04IKID\x12\x18\n" +
	"\aProfile\x18\x04 \x01(\tR\aProfile\x122\n" +
	"\x06Status\x18\x05 \x01(\x0e2\x1a.pb.CertificateStatus.EnumR\x06Status\x12&\n" +
	"\x0eExpiringBefore\x18\x06 \x01(\tR\x0eExpiringBefore\x12\x14\n" +
	"\x05Limit\x18\a \x01(\rR\x05Limit\x12\x16\n" +
	"\x06Offset\x18\b \x01(\rR\x06Offset\x12\x16\n" +
	"\x06Cursor\x18\t \x01(\tR\x06Cursor\"\xb4\x01\n" +
	"\x1eListRevokedCertificatesRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12\x1c\n" +
	"\tProjectID\x18\x02 \x01(\tR\tProjectID\x12\x12\n" +
	"\x04IKID\x18\x03 \x01(\tR\x04IKID\x12\x14\n" +
	"\x05Limit\x18\x04 \x01(\rR\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x05 \x01(\rR\x06Offset\x12\x16\n" +
	"\x06Cursor\x18\x06 \x01(\tR\x06Cursor\"\x9d\x02\n" +
	"\x18RevokeCertificateRequest\x12\x1a\n" +
	"\x05OrgID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x05OrgID\x12%\n" +
	"\x02ID\x18\x02 \x01(\tB\x15\xf2\xf3\x18\x11SKID,IssuerSerialR\x02ID\x12'\n" +
	"\x04SKID\x18\x03 \x01(\tB\x13\xf2\xf3\x18\x0fID,IssuerSerialR\x04SKID\x12A\n" +
	"\fIssuerSerial\x18\x04 \x01(\v2\x10.pb.IssuerSerialB\v\xf2\xf3\x18\aID,SKIDR\fIssuerSerial\x12+\n" +
	"\x06Reason\x18\x05 \x01(\x0e2\x13.pb.ReasonCode.EnumR\x06Reason\x12%\n" +
	"\n" +
	"ReasonText\x18\x06 \x01(\tB\x05\x80\xf4\x18\x84\x02R\n" +
	"ReasonText\"H\n" +
	"\x13CertificateResponse\x121\n" +
	"\vCertificate\x18\x01 \x01(\v2\x0f.pb.CertificateR\vCertificate\"u\n" +
	"\x14CertificatesResponse\x123\n" +
	"\fCertificates\x18\x01 \x03(\v2\x0f.pb.CertificateR\fCertificates\x12(\n" +
	"\bNextPage\x18\x02 \x01(\v2\f.pb.NextPageR\bNextPage\"N\n" +
	"\x1aRevokedCertificateResponse\x120\n" +
	"\aRevoked\x18\x01 \x01(\v2\x16.pb.RevokedCertificateR\aRevoked\"\x91\x01\n" +
	"\x1bRevokedCertificatesResponse\x12H\n" +
	"\x13RevokedCertificates\x18\x01 \x03(\v2\x16.pb.RevokedCertificateR\x13RevokedCertificates\x12(\n" +
	"\bNextPage\x18\x02 \x01(\v2\f.pb.NextPageR\bNextPage\"?\n" +
	"\rGetCrlRequest\x12\x14\n" +
	"\x05OrgID\x18\x01 \x01(\tR\x05OrgID\x12\x18\n" +
	"\x04IKID\x18\x02 \x01(\tB\x04\xe8\xf3\x18\x01R\x04IKID\"T\n" +
	"\x12PublishCrlsRequest\x12\x14\n" +
	"\x05OrgID\x18\x01 \x01(\tR\x05OrgID\x12\x12\n" +
	"\x04IKID\x18\x02 \x01(\tR\x04IKID\x12\x14\n" +
	"\x05Force\x18\x03 \x01(\bR\x05Force\"+\n" +
	"\fCrlsResponse\x12\x1b\n" +
	"\x04Crls\x18\x01 \x03(\v2\a.pb.CrlR\x04Crls\"(\n" +
	"\vCrlResponse\x12\x19\n" +
	"\x03Crl\x18\x01 \x01(\v2\a.pb.CrlR\x03Crl\"%\n" +
	"\vOCSPRequest\x12\x16\n" +
	"\x03Der\x18\x01 \x01(\fB\x04\xe8\xf3\x18\x01R\x03Der\" \n" +
	"\fOCSPResponse\x12\x10\n" +
	"\x03Der\x18\x01 \x01(\fR\x03Der2\xea\x0e\n" +
	"\x02CA\x12L\n" +
	"\x0eRegisterIssuer\x12\x19.pb.RegisterIssuerRequest\x1a\n" +
	".pb.Issuer\"\x13\xfaB\x05Admin\x92C\bca:write\x12H\n" +
	"\fUpdateIssuer\x12\x17.pb.UpdateIssuerRequest\x1a\n" +
	".pb.Issuer\"\x13\xfaB\x05Admin\x92C\bca:write\x12H\n" +
	"\fImportIssuer\x12\x17.pb.ImportIssuerRequest\x1a\n" +
	".pb.Issuer\"\x13\xfaB\x05Admin\x92C\bca:write\x12L\n" +
	"\x0eActivateIssuer\x12\x19.pb.ActivateIssuerRequest\x1a\n" +
	".pb.Issuer\"\x13\xfaB\x05Admin\x92C\bca:write\x12I\n" +
	"\tGetIssuer\x12\x14.pb.GetIssuerRequest\x1a\n" +
	".pb.Issuer\"\x1a\xfaB\rViewer,APIKey\x92C\aca:read\x12V\n" +
	"\vListIssuers\x12\x16.pb.ListIssuersRequest\x1a\x13.pb.IssuersResponse\"\x1a\xfaB\rViewer,APIKey\x92C\aca:read\x12Q\n" +
	"\fRegisterRoot\x12\x17.pb.RegisterRootRequest\x1a\x13.pb.RootCertificate\"\x13\xfaB\x05Admin\x92C\bca:write\x12P\n" +
	"\tListRoots\x12\x14.pb.ListRootsRequest\x1a\x11.pb.RootsResponse\"\x1a\xfaB\rViewer,APIKey\x92C\aca:read\x12S\n" +
	"\x0fRegisterProfile\x12\x1a.pb.RegisterProfileRequest\x1a\x0f.pb.CertProfile\"\x13\xfaB\x05Admin\x92C\bca:write\x12P\n" +
	"\n" +
	"GetProfile\x12\x15.pb.GetProfileRequest\x1a\x0f.pb.CertProfile\"\x1a\xfaB\rViewer,APIKey\x92C\aca:read\x12Y\n" +
	"\fListProfiles\x12\x17.pb.ListProfilesRequest\x1a\x14.pb.ProfilesResponse\"\x1a\xfaB\rViewer,APIKey\x92C\aca:read\x12V\n" +
	"\rDeleteProfile\x12\x18.pb.DeleteProfileRequest\x1a\x16.google.protobuf.Empty\"\x13\xfaB\x05Admin\x92C\bca:write\x12d\n" +
	"\x0fSignCertificate\x12\x1a.pb.SignCertificateRequest\x1a\x17.pb.CertificateResponse\"\x1c\xfaB\vUser,APIKey\x92C\vcerts:issue\x12c\n" +
	"\x0eGetCertificate\x12\x19.pb.GetCertificateRequest\x1a\x17.pb.CertificateResponse\"\x1d\xfaB\rViewer,APIKey\x92C\n" +
	"certs:read\x12h\n" +
	"\x10ListCertificates\x12\x1b.pb.ListCertificatesRequest\x1a\x18.pb.CertificatesResponse\"\x1d\xfaB\rViewer,APIKey\x92C\n" +
	"certs:read\x12r\n" +
	"\x16UpdateCertificateLabel\x12!.pb.UpdateCertificateLabelRequest\x1a\x17.pb.CertificateResponse\"\x1c\xfaB\vUser,APIKey\x92C\vcerts:issue\x12y\n" +
	"\x11RevokeCertificate\x12\x1c.pb.RevokeCertificateRequest\x1a\x1e.pb.RevokedCertificateResponse\"&\xfaB\x14User,APIKey,Security\x92C\fcerts:revoke\x12}\n" +
	"\x17ListRevokedCertificates\x12\".pb.ListRevokedCertificatesRequest\x1a\x1f.pb.RevokedCertificatesResponse\"\x1d\xfaB\rViewer,APIKey\x92C\n" +
	"certs:read\x12K\n" +
	"\x06GetCRL\x12\x11.pb.GetCrlRequest\x1a\x0f.pb.CrlResponse\"\x1d\xfaB\rViewer,APIKey\x92C\n" +
	"certs:read\x12U\n" +
	"\vPublishCrls\x12\x16.pb.PublishCrlsRequest\x1a\x10.pb.CrlsResponse\"\x1c\xfaB\x0eAdmin,Security\x92C\bca:write\x12K\n" +
	"\bSignOCSP\x12\x0f.pb.OCSPRequest\x1a\x10.pb.OCSPResponse\"\x1c\xfaB\x0eAdmin,Security\x92C\bca:writeB/Z-github.com/effective-security/trustyca/api/pbb\x06proto3"

var (
	file_ca_proto_rawDescOnce sync.Once
	file_ca_proto_rawDescData []byte
)

func file_ca_proto_rawDescGZIP() []byte {
	file_ca_proto_rawDescOnce.Do(func() {
		file_ca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ca_proto_rawDesc), len(file_ca_proto_rawDesc)))
	})
	return file_ca_proto_rawDescData
}

var file_ca_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_ca_proto_goTypes = []any{
	(*RegisterIssuerRequest)(nil),          // 0: pb.RegisterIssuerRequest
	(*ImportIssuerRequest)(nil),            // 1: pb.ImportIssuerRequest
	(*ActivateIssuerRequest)(nil),          // 2: pb.ActivateIssuerRequest
	(*GetIssuerRequest)(nil),               // 3: pb.GetIssuerRequest
	(*ListIssuersRequest)(nil),             // 4: pb.ListIssuersRequest
	(*IssuersResponse)(nil),                // 5: pb.IssuersResponse
	(*UpdateIssuerRequest)(nil),            // 6: pb.UpdateIssuerRequest
	(*RegisterRootRequest)(nil),            // 7: pb.RegisterRootRequest
	(*ListRootsRequest)(nil),               // 8: pb.ListRootsRequest
	(*RootsResponse)(nil),                  // 9: pb.RootsResponse
	(*RegisterProfileRequest)(nil),         // 10: pb.RegisterProfileRequest
	(*GetProfileRequest)(nil),              // 11: pb.GetProfileRequest
	(*ListProfilesRequest)(nil),            // 12: pb.ListProfilesRequest
	(*ProfilesResponse)(nil),               // 13: pb.ProfilesResponse
	(*DeleteProfileRequest)(nil),           // 14: pb.DeleteProfileRequest
	(*SignCertificateRequest)(nil),         // 15: pb.SignCertificateRequest
	(*UpdateCertificateLabelRequest)(nil),  // 16: pb.UpdateCertificateLabelRequest
	(*GetCertificateRequest)(nil),          // 17: pb.GetCertificateRequest
	(*ListCertificatesRequest)(nil),        // 18: pb.ListCertificatesRequest
	(*ListRevokedCertificatesRequest)(nil), // 19: pb.ListRevokedCertificatesRequest
	(*RevokeCertificateRequest)(nil),       // 20: pb.RevokeCertificateRequest
	(*CertificateResponse)(nil),            // 21: pb.CertificateResponse
	(*CertificatesResponse)(nil),           // 22: pb.CertificatesResponse
	(*RevokedCertificateResponse)(nil),     // 23: pb.RevokedCertificateResponse
	(*RevokedCertificatesResponse)(nil),    // 24: pb.RevokedCertificatesResponse
	(*GetCrlRequest)(nil),                  // 25: pb.GetCrlRequest
	(*PublishCrlsRequest)(nil),             // 26: pb.PublishCrlsRequest
	(*CrlsResponse)(nil),                   // 27: pb.CrlsResponse
	(*CrlResponse)(nil),                    // 28: pb.CrlResponse
	(*OCSPRequest)(nil),                    // 29: pb.OCSPRequest
	(*OCSPResponse)(nil),                   // 30: pb.OCSPResponse
	nil,                                    // 31: pb.SignCertificateRequest.MetadataEntry
	nil,                                    // 32: pb.UpdateCertificateLabelRequest.MetadataEntry
	(AuthorityType_Enum)(0),                // 33: pb.AuthorityType.Enum
	(*X509Subject)(nil),                    // 34: pb.X509Subject
	(*KeySpec)(nil),                        // 35: pb.KeySpec
	(*IssuerConfig)(nil),                   // 36: pb.IssuerConfig
	(*X509Extension)(nil),                  // 37: pb.X509Extension
	(IssuerStatus_Enum)(0),                 // 38: pb.IssuerStatus.Enum
	(*Issuer)(nil),                         // 39: pb.Issuer
	(*NextPage)(nil),                       // 40: pb.NextPage
	(Trust_Enum)(0),                        // 41: pb.Trust.Enum
	(*RootCertificate)(nil),                // 42: pb.RootCertificate
	(*CertProfile)(nil),                    // 43: pb.CertProfile
	(EncodingFormat_Enum)(0),               // 44: pb.EncodingFormat.Enum
	(*IssuerSerial)(nil),                   // 45: pb.IssuerSerial
	(CertificateStatus_Enum)(0),            // 46: pb.CertificateStatus.Enum
	(ReasonCode_Enum)(0),                   // 47: pb.ReasonCode.Enum
	(*Certificate)(nil),                    // 48: pb.Certificate
	(*RevokedCertificate)(nil),             // 49: pb.RevokedCertificate
	(*Crl)(nil),                            // 50: pb.Crl
	(*emptypb.Empty)(nil),                  // 51: google.protobuf.Empty
}
var file_ca_proto_depIdxs = []int32{
	33, // 0: pb.RegisterIssuerRequest.Type:type_name -> pb.AuthorityType.Enum
	34, // 1: pb.RegisterIssuerRequest.Subject:type_name -> pb.X509Subject
	35, // 2: pb.RegisterIssuerRequest.KeySpec:type_name -> pb.KeySpec
	36, // 3: pb.RegisterIssuerRequest.Config:type_name -> pb.IssuerConfig
	37, // 4: pb.RegisterIssuerRequest.Extensions:type_name -> pb.X509Extension
	33, // 5: pb.ImportIssuerRequest.Type:type_name -> pb.AuthorityType.Enum
	36, // 6: pb.ImportIssuerRequest.Config:type_name -> pb.IssuerConfig
	38, // 7: pb.ListIssuersRequest.Status:type_name -> pb.IssuerStatus.Enum
	33, // 8: pb.ListIssuersRequest.Type:type_name -> pb.AuthorityType.Enum
	39, // 9: pb.IssuersResponse.Issuers:type_name -> pb.Issuer
	40, // 10: pb.IssuersResponse.NextPage:type_name -> pb.NextPage
	36, // 11: pb.UpdateIssuerRequest.Config:type_name -> pb.IssuerConfig
	38, // 12: pb.UpdateIssuerRequest.Status:type_name -> pb.IssuerStatus.Enum
	41, // 13: pb.RegisterRootRequest.Trust:type_name -> pb.Trust.Enum
	42, // 14: pb.RootsResponse.Roots:type_name -> pb.RootCertificate
	40, // 15: pb.RootsResponse.NextPage:type_name -> pb.NextPage
	43, // 16: pb.RegisterProfileRequest.Profile:type_name -> pb.CertProfile
	43, // 17: pb.ProfilesResponse.Profiles:type_name -> pb.CertProfile
	40, // 18: pb.ProfilesResponse.NextPage:type_name -> pb.NextPage
	44, // 19: pb.SignCertificateRequest.RequestFormat:type_name -> pb.EncodingFormat.Enum
	34, // 20: pb.SignCertificateRequest.Subject:type_name -> pb.X509Subject
	37, // 21: pb.SignCertificateRequest.Extensions:type_name -> pb.X509Extension
	31, // 22: pb.SignCertificateRequest.Metadata:type_name -> pb.SignCertificateRequest.MetadataEntry
	32, // 23: pb.UpdateCertificateLabelRequest.Metadata:type_name -> pb.UpdateCertificateLabelRequest.MetadataEntry
	45, // 24: pb.GetCertificateRequest.IssuerSerial:type_name -> pb.IssuerSerial
	46, // 25: pb.ListCertificatesRequest.Status:type_name -> pb.CertificateStatus.Enum
	45, // 26: pb.RevokeCertificateRequest.IssuerSerial:type_name -> pb.IssuerSerial
	47, // 27: pb.RevokeCertificateRequest.Reason:type_name -> pb.ReasonCode.Enum
	48, // 28: pb.CertificateResponse.Certificate:type_name -> pb.Certificate
	48, // 29: pb.CertificatesResponse.Certificates:type_name -> pb.Certificate
	40, // 30: pb.CertificatesResponse.NextPage:type_name -> pb.NextPage
	49, // 31: pb.RevokedCertificateResponse.Revoked:type_name -> pb.RevokedCertificate
	49, // 32: pb.RevokedCertificatesResponse.RevokedCertificates:type_name -> pb.RevokedCertificate
	40, // 33: pb.RevokedCertificatesResponse.NextPage:type_name -> pb.NextPage
	50, // 34: pb.CrlsResponse.Crls:type_name -> pb.Crl
	50, // 35: pb.CrlResponse.Crl:type_name -> pb.Crl
	0,  // 36: pb.CA.RegisterIssuer:input_type -> pb.RegisterIssuerRequest
	6,  // 37: pb.CA.UpdateIssuer:input_type -> pb.UpdateIssuerRequest
	1,  // 38: pb.CA.ImportIssuer:input_type -> pb.ImportIssuerRequest
	2,  // 39: pb.CA.ActivateIssuer:input_type -> pb.ActivateIssuerRequest
	3,  // 40: pb.CA.GetIssuer:input_type -> pb.GetIssuerRequest
	4,  // 41: pb.CA.ListIssuers:input_type -> pb.ListIssuersRequest
	7,  // 42: pb.CA.RegisterRoot:input_type -> pb.RegisterRootRequest
	8,  // 43: pb.CA.ListRoots:input_type -> pb.ListRootsRequest
	10, // 44: pb.CA.RegisterProfile:input_type -> pb.RegisterProfileRequest
	11, // 45: pb.CA.GetProfile:input_type -> pb.GetProfileRequest
	12, // 46: pb.CA.ListProfiles:input_type -> pb.ListProfilesRequest
	14, // 47: pb.CA.DeleteProfile:input_type -> pb.DeleteProfileRequest
	15, // 48: pb.CA.SignCertificate:input_type -> pb.SignCertificateRequest
	17, // 49: pb.CA.GetCertificate:input_type -> pb.GetCertificateRequest
	18, // 50: pb.CA.ListCertificates:input_type -> pb.ListCertificatesRequest
	16, // 51: pb.CA.UpdateCertificateLabel:input_type -> pb.UpdateCertificateLabelRequest
	20, // 52: pb.CA.RevokeCertificate:input_type -> pb.RevokeCertificateRequest
	19, // 53: pb.CA.ListRevokedCertificates:input_type -> pb.ListRevokedCertificatesRequest
	25, // 54: pb.CA.GetCRL:input_type -> pb.GetCrlRequest
	26, // 55: pb.CA.PublishCrls:input_type -> pb.PublishCrlsRequest
	29, // 56: pb.CA.SignOCSP:input_type -> pb.OCSPRequest
	39, // 57: pb.CA.RegisterIssuer:output_type -> pb.Issuer
	39, // 58: pb.CA.UpdateIssuer:output_type -> pb.Issuer
	39, // 59: pb.CA.ImportIssuer:output_type -> pb.Issuer
	39, // 60: pb.CA.ActivateIssuer:output_type -> pb.Issuer
	39, // 61: pb.CA.GetIssuer:output_type -> pb.Issuer
	5,  // 62: pb.CA.ListIssuers:output_type -> pb.IssuersResponse
	42, // 63: pb.CA.RegisterRoot:output_type -> pb.RootCertificate
	9,  // 64: pb.CA.ListRoots:output_type -> pb.RootsResponse
	43, // 65: pb.CA.RegisterProfile:output_type -> pb.CertProfile
	43, // 66: pb.CA.GetProfile:output_type -> pb.CertProfile
	13, // 67: pb.CA.ListProfiles:output_type -> pb.ProfilesResponse
	51, // 68: pb.CA.DeleteProfile:output_type -> google.protobuf.Empty
	21, // 69: pb.CA.SignCertificate:output_type -> pb.CertificateResponse
	21, // 70: pb.CA.GetCertificate:output_type -> pb.CertificateResponse
	22, // 71: pb.CA.ListCertificates:output_type -> pb.CertificatesResponse
	21, // 72: pb.CA.UpdateCertificateLabel:output_type -> pb.CertificateResponse
	23, // 73: pb.CA.RevokeCertificate:output_type -> pb.RevokedCertificateResponse
	24, // 74: pb.CA.ListRevokedCertificates:output_type -> pb.RevokedCertificatesResponse
	28, // 75: pb.CA.GetCRL:output_type -> pb.CrlResponse
	27, // 76: pb.CA.PublishCrls:output_type -> pb.CrlsResponse
	30, // 77: pb.CA.SignOCSP:output_type -> pb.OCSPResponse
	57, // [57:78] is the sub-list for method output_type
	36, // [36:57] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_ca_proto_init() }
func file_ca_proto_init() {
	if File_ca_proto != nil {
		return
	}
	file_types_proto_init()
	file_pkix_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ca_proto_rawDesc), len(file_ca_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ca_proto_goTypes,
		DependencyIndexes: file_ca_proto_depIdxs,
		MessageInfos:      file_ca_proto_msgTypes,
	}.Build()
	File_ca_proto = out.File
	file_ca_proto_goTypes = nil
	file_ca_proto_depIdxs = nil
}
