// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: cis.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/effective-security/protoc-gen-go/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetIssuerInfoRequest specifies an issuer by IKID
type GetIssuerInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IKID specifies Issuer Key ID
	IKID          string `protobuf:"bytes,1,opt,name=IKID,proto3" json:"IKID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIssuerInfoRequest) Reset() {
	*x = GetIssuerInfoRequest{}
	mi := &file_cis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIssuerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIssuerInfoRequest) ProtoMessage() {}

func (x *GetIssuerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIssuerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetIssuerInfoRequest) Descriptor() ([]byte, []int) {
	return file_cis_proto_rawDescGZIP(), []int{0}
}

func (x *GetIssuerInfoRequest) GetIKID() string {
	if x != nil {
		return x.IKID
	}
	return ""
}

// IssuerInfo provides the public view of an issuer
type IssuerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Label of the issuer
	Label string `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	// Type of the authority
	Type AuthorityType_Enum `protobuf:"varint,2,opt,name=Type,proto3,enum=pb.AuthorityType_Enum" json:"Type,omitempty"`
	// Status of the issuer
	Status IssuerStatus_Enum `protobuf:"varint,3,opt,name=Status,proto3,enum=pb.IssuerStatus_Enum" json:"Status,omitempty"`
	// SKID provides Subject Key Identifier
	SKID string `protobuf:"bytes,4,opt,name=SKID,proto3" json:"SKID,omitempty"`
	// Subject name
	Subject string `protobuf:"bytes,5,opt,name=Subject,proto3" json:"Subject,omitempty"`
	// NotBefore in RFC3339 format
	NotBefore string `protobuf:"bytes,6,opt,name=NotBefore,proto3" json:"NotBefore,omitempty"`
	// NotAfter in RFC3339 format
	NotAfter string `protobuf:"bytes,7,opt,name=NotAfter,proto3" json:"NotAfter,omitempty"`
	// Certificate provides the issuer certificate in PEM format
	Certificate string `protobuf:"bytes,8,opt,name=Certificate,proto3" json:"Certificate,omitempty"`
	// Intermediates provides the intermediate CA certificates in PEM format
	Intermediates string `protobuf:"bytes,9,opt,name=Intermediates,proto3" json:"Intermediates,omitempty"`
	// Root provides the Root CA certificate in PEM format
	Root string `protobuf:"bytes,10,opt,name=Root,proto3" json:"Root,omitempty"`
	// CrlURL is the CRL Distribution Point
	CrlURL string `protobuf:"bytes,11,opt,name=CrlURL,proto3" json:"CrlURL,omitempty"`
	// OcspURL is the OCSP responder URL
	OcspURL string `protobuf:"bytes,12,opt,name=OcspURL,proto3" json:"OcspURL,omitempty"`
	// AiaURL is the AIA issuer certificate URL
	AiaURL        string `protobuf:"bytes,13,opt,name=AiaURL,proto3" json:"AiaURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerInfo) Reset() {
	*x = IssuerInfo{}
	mi := &file_cis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerInfo) ProtoMessage() {}

func (x *IssuerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerInfo.ProtoReflect.Descriptor instead.
func (*IssuerInfo) Descriptor() ([]byte, []int) {
	return file_cis_proto_rawDescGZIP(), []int{1}
}

func (x *IssuerInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *IssuerInfo) GetType() AuthorityType_Enum {
	if x != nil {
		return x.Type
	}
	return AuthorityType_Unknown
}

func (x *IssuerInfo) GetStatus() IssuerStatus_Enum {
	if x != nil {
		return x.Status
	}
	return IssuerStatus_Unknown
}

func (x *IssuerInfo) GetSKID() string {
	if x != nil {
		return x.SKID
	}
	return ""
}

func (x *IssuerInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IssuerInfo) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *IssuerInfo) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *IssuerInfo) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *IssuerInfo) GetIntermediates() string {
	if x != nil {
		return x.Intermediates
	}
	return ""
}

func (x *IssuerInfo) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *IssuerInfo) GetCrlURL() string {
	if x != nil {
		return x.CrlURL
	}
	return ""
}

func (x *IssuerInfo) GetOcspURL() string {
	if x != nil {
		return x.OcspURL
	}
	return ""
}

func (x *IssuerInfo) GetAiaURL() string {
	if x != nil {
		return x.AiaURL
	}
	return ""
}

// GetCertificateInfoRequest specifies a certificate by ID, SKID, Sha256 or
// issuer and serial number
type GetCertificateInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID specifies certificate ID
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// SKID specifies Subject Key ID to search
	SKID string `protobuf:"bytes,2,opt,name=SKID,proto3" json:"SKID,omitempty"`
	// Sha256 specifies the certificate thumbprint to search
	Sha256 string `protobuf:"bytes,3,opt,name=Sha256,proto3" json:"Sha256,omitempty"`
	// IssuerSerial specifies Issuer Key ID and certificate serial number
	IssuerSerial  *IssuerSerial `protobuf:"bytes,4,opt,name=IssuerSerial,proto3" json:"IssuerSerial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateInfoRequest) Reset() {
	*x = GetCertificateInfoRequest{}
	mi := &file_cis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateInfoRequest) ProtoMessage() {}

func (x *GetCertificateInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateInfoRequest) Descriptor() ([]byte, []int) {
	return file_cis_proto_rawDescGZIP(), []int{2}
}

func (x *GetCertificateInfoRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetCertificateInfoRequest) GetSKID() string {
	if x != nil {
		return x.SKID
	}
	return ""
}

func (x *GetCertificateInfoRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *GetCertificateInfoRequest) GetIssuerSerial() *IssuerSerial {
	if x != nil {
		return x.IssuerSerial
	}
	return nil
}

// CertificateStatusResponse returns the revocation status of a certificate
type CertificateStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IKID provides Issuer Key Identifier
	IKID string `protobuf:"bytes,1,opt,name=IKID,proto3" json:"IKID,omitempty"`
	// SerialNumber provides Serial Number
	SerialNumber string `protobuf:"bytes,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	// Status of the certificate
	Status CertificateStatus_Enum `protobuf:"varint,3,opt,name=Status,proto3,enum=pb.CertificateStatus_Enum" json:"Status,omitempty"`
	// NotAfter in RFC3339 format
	NotAfter string `protobuf:"bytes,4,opt,name=NotAfter,proto3" json:"NotAfter,omitempty"`
	// RevokedAt in RFC3339 format, when revoked
	RevokedAt string `protobuf:"bytes,5,opt,name=RevokedAt,proto3" json:"RevokedAt,omitempty"`
	// Reason of the revocation, when revoked
	Reason        ReasonCode_Enum `protobuf:"varint,6,opt,name=Reason,proto3,enum=pb.ReasonCode_Enum" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateStatusResponse) Reset() {
	*x = CertificateStatusResponse{}
	mi := &file_cis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateStatusResponse) ProtoMessage() {}

func (x *CertificateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateStatusResponse.ProtoReflect.Descriptor instead.
func (*CertificateStatusResponse) Descriptor() ([]byte, []int) {
	return file_cis_proto_rawDescGZIP(), []int{3}
}

func (x *CertificateStatusResponse) GetIKID() string {
	if x != nil {
		return x.IKID
	}
	return ""
}

func (x *CertificateStatusResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CertificateStatusResponse) GetStatus() CertificateStatus_Enum {
	if x != nil {
		return x.Status
	}
	return CertificateStatus_Unknown
}

func (x *CertificateStatusResponse) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *CertificateStatusResponse) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

func (x *CertificateStatusResponse) GetReason() ReasonCode_Enum {
	if x != nil {
		return x.Reason
	}
	return ReasonCode_Unspecified
}

var File_cis_proto protoreflect.FileDescriptor

const file_cis_proto_rawDesc = "" +
	"\n" +
	"\tcis.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x18es/api/annotations.proto\x1a\vtypes.proto\x1a\n" +
	"pkix.proto\x1a\bca.proto\"0\n" +
	"\x14GetIssuerInfoRequest\x12\x18\n" +
	"\x04IKID\x18\x01 \x01(\tB\x04\xe8\xf3\x18\x01R\x04IKID\"\x8b\x03\n" +
	"\n" +
	"IssuerInfo\x12\x14\n" +
	"\x05Label\x18\x01 \x01(\tR\x05Label\x12*\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x16.pb.AuthorityType.EnumR\x04Type\x12-\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x15.pb.IssuerStatus.EnumR\x06Status\x12\x12\n" +
	"\x04SKID\x18\x04 \x01(\tR\x04SKID\x12\x18\n" +
	"\aSubject\x18\x05 \x01(\tR\aSubject\x12\x1c\n" +
	"\tNotBefore\x18\x06 \x01(\tR\tNotBefore\x12\x1a\n" +
	"\bNotAfter\x18\a \x01(\tR\bNotAfter\x12 \n" +
	"\vCertificate\x18\b \x01(\tR\vCertificate\x12$\n" +
	"\rIntermediates\x18\t \x01(\tR\rIntermediates\x12\x12\n" +
	"\x04Root\x18\n" +
	" \x01(\tR\x04Root\x12\x16\n" +
	"\x06CrlURL\x18\v \x01(\tR\x06CrlURL\x12\x18\n" +
	"\aOcspURL\x18\f \x01(\tR\aOcspURL\x12\x16\n" +
	"\x06AiaURL\x18\r \x01(\tR\x06AiaURL\"\xf5\x01\n" +
	"\x19GetCertificateInfoRequest\x12,\n" +
	"\x02ID\x18\x01 \x01(\tB\x1c\xf2\xf3\x18\x18SKID,Sha256,IssuerSerialR\x02ID\x12.\n" +
	"\x04SKID\x18\x02 \x01(\tB\x1a\xf2\xf3\x18\x16ID,Sha256,IssuerSerialR\x04SKID\x120\n" +
	"\x06Sha256\x18\x03 \x01(\tB\x18\xf2\xf3\x18\x14ID,SKID,IssuerSerialR\x06Sha256\x12H\n" +
	"\fIssuerSerial\x18\x04 \x01(\v2\x10.pb.IssuerSerialB\x12\xf2\xf3\x18\x0eID,SKID,Sha256R\fIssuerSerial\"\xee\x01\n" +
	"\x19CertificateStatusResponse\x12\x12\n" +
	"\x04IKID\x18\x01 \x01(\tR\x04IKID\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\tR\fSerialNumber\x122\n" +
	"\x06Status\x18\x03 \x01(\x0e2\x1a.pb.CertificateStatus.EnumR\x06Status\x12\x1a\n" +
	"\bNotAfter\x18\x04 \x01(\tR\bNotAfter\x12\x1c\n" +
	"\tRevokedAt\x18\x05 \x01(\tR\tRevokedAt\x12+\n" +
	"\x06Reason\x18\x06 \x01(\x0e2\x13.pb.ReasonCode.EnumR\x06Reason2\xe1\x03\n" +
	"\x03CIS\x12P\n" +
	"\bGetRoots\x12\x14.pb.ListRootsRequest\x1a\x11.pb.RootsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/pb.CIS/GetRoots\x12S\n" +
	"\tGetIssuer\x12\x18.pb.GetIssuerInfoRequest\x1a\x0e.pb.IssuerInfo\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/pb.CIS/GetIssuer\x12k\n" +
	"\x0eGetCertificate\x12\x1d.pb.GetCertificateInfoRequest\x1a\x17.pb.CertificateResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/pb.CIS/GetCertificate\x12}\n" +
	"\x14GetCertificateStatus\x12\x1d.pb.GetCertificateInfoRequest\x1a\x1d.pb.CertificateStatusResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/pb.CIS/GetCertificateStatus\x12G\n" +
	"\x06GetCRL\x12\x11.pb.GetCrlRequest\x1a\x0f.pb.CrlResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/pb.CIS/GetCRLB/Z-github.com/effective-security/trustyca/api/pbb\x06proto3"

var (
	file_cis_proto_rawDescOnce sync.Once
	file_cis_proto_rawDescData []byte
)

func file_cis_proto_rawDescGZIP() []byte {
	file_cis_proto_rawDescOnce.Do(func() {
		file_cis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cis_proto_rawDesc), len(file_cis_proto_rawDesc)))
	})
	return file_cis_proto_rawDescData
}

var file_cis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cis_proto_goTypes = []any{
	(*GetIssuerInfoRequest)(nil),      // 0: pb.GetIssuerInfoRequest
	(*IssuerInfo)(nil),                // 1: pb.IssuerInfo
	(*GetCertificateInfoRequest)(nil), // 2: pb.GetCertificateInfoRequest
	(*CertificateStatusResponse)(nil), // 3: pb.CertificateStatusResponse
	(AuthorityType_Enum)(0),           // 4: pb.AuthorityType.Enum
	(IssuerStatus_Enum)(0),            // 5: pb.IssuerStatus.Enum
	(*IssuerSerial)(nil),              // 6: pb.IssuerSerial
	(CertificateStatus_Enum)(0),       // 7: pb.CertificateStatus.Enum
	(ReasonCode_Enum)(0),              // 8: pb.ReasonCode.Enum
	(*ListRootsRequest)(nil),          // 9: pb.ListRootsRequest
	(*GetCrlRequest)(nil),             // 10: pb.GetCrlRequest
	(*RootsResponse)(nil),             // 11: pb.RootsResponse
	(*CertificateResponse)(nil),       // 12: pb.CertificateResponse
	(*CrlResponse)(nil),               // 13: pb.CrlResponse
}
var file_cis_proto_depIdxs = []int32{
	4,  // 0: pb.IssuerInfo.Type:type_name -> pb.AuthorityType.Enum
	5,  // 1: pb.IssuerInfo.Status:type_name -> pb.IssuerStatus.Enum
	6,  // 2: pb.GetCertificateInfoRequest.IssuerSerial:type_name -> pb.IssuerSerial
	7,  // 3: pb.CertificateStatusResponse.Status:type_name -> pb.CertificateStatus.Enum
	8,  // 4: pb.CertificateStatusResponse.Reason:type_name -> pb.ReasonCode.Enum
	9,  // 5: pb.CIS.GetRoots:input_type -> pb.ListRootsRequest
	0,  // 6: pb.CIS.GetIssuer:input_type -> pb.GetIssuerInfoRequest
	2,  // 7: pb.CIS.GetCertificate:input_type -> pb.GetCertificateInfoRequest
	2,  // 8: pb.CIS.GetCertificateStatus:input_type -> pb.GetCertificateInfoRequest
	10, // 9: pb.CIS.GetCRL:input_type -> pb.GetCrlRequest
	11, // 10: pb.CIS.GetRoots:output_type -> pb.RootsResponse
	1,  // 11: pb.CIS.GetIssuer:output_type -> pb.IssuerInfo
	12, // 12: pb.CIS.GetCertificate:output_type -> pb.CertificateResponse
	3,  // 13: pb.CIS.GetCertificateStatus:output_type -> pb.CertificateStatusResponse
	13, // 14: pb.CIS.GetCRL:output_type -> pb.CrlResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cis_proto_init() }
func file_cis_proto_init() {
	if File_cis_proto != nil {
		return
	}
	file_types_proto_init()
	file_pkix_proto_init()
	file_ca_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cis_proto_rawDesc), len(file_cis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cis_proto_goTypes,
		DependencyIndexes: file_cis_proto_depIdxs,
		MessageInfos:      file_cis_proto_msgTypes,
	}.Build()
	File_cis_proto = out.File
	file_cis_proto_goTypes = nil
	file_cis_proto_depIdxs = nil
}
