// Code generated by protoc-gen-go-json. DO NOT EDIT.

package pb

import (
	"encoding/json"
	reflect "reflect"
	"strings"

	"github.com/effective-security/protoc-gen-go/api"
	"github.com/effective-security/x/enum"
)

const (
	Display_EventType_Unknown              = "Unknown"
	Display_EventType_OrgCreated           = "Org Created"
	Display_EventType_OrgUpdated           = "Org Updated"
	Display_EventType_OrgDeleted           = "Org Deleted"
	Display_EventType_OrgMemberAdded       = "Org Member Added"
	Display_EventType_OrgMemberRemoved     = "Org Member Removed"
	Display_EventType_OrgMemberRoleChanged = "Org Member Role Changed"
	Display_EventType_OrgMemberInvited     = "Org Member Invited"
	Display_EventType_OrgMemberAccepted    = "Org Member Accepted"
	Display_IDP_Undefined                  = "undefined"
	Display_IDP_Google                     = "google"
	Display_IDP_Github                     = "github"
	Display_IDP_Gitlab                     = "gitlab"
	Display_IDP_Local                      = "local"
	Display_ItemStatus_Unknown             = "Unknown"
	Display_ItemStatus_Inactive            = "Inactive"
	Display_ItemStatus_Active              = "Active"
	Display_ItemStatus_Invalid             = "Invalid"
	Display_PermissionsScope_None          = "None"
	Display_PermissionsScope_ReadOnly      = "Read Only"
	Display_PermissionsScope_Restricted    = "Restricted"
	Display_PermissionsScope_All           = "All"
	Display_Role_None                      = "None"
	Display_Role_APIKey                    = "API Key"
	Display_Role_User                      = "User"
	Display_Role_Support                   = "Support"
	Display_Role_Admin                     = "Admin"
	Display_Role_Owner                     = "Owner"
)

var EnumNameTypes = map[string]reflect.Type{
	"pb.EventType.Enum":        reflect.TypeOf(EventType_Enum(0)),
	"pb.IDP.Enum":              reflect.TypeOf(IDP_Enum(0)),
	"pb.ItemStatus.Enum":       reflect.TypeOf(ItemStatus_Enum(0)),
	"pb.PermissionsScope.Enum": reflect.TypeOf(PermissionsScope_Enum(0)),
	"pb.Role.Enum":             reflect.TypeOf(Role_Enum(0)),
}

//
// EventType_Enum
//

type EventType_EnumSlice []EventType_Enum

const EventType_Enum_SupportedNamesHelp = "Unknown,OrgCreated,OrgUpdated,OrgDeleted,OrgMemberAdded,OrgMemberRemoved,OrgMemberRoleChanged,OrgMemberInvited,OrgMemberAccepted"

// ValuesMap returns a map of enum values
func (s EventType_Enum) ValuesMap() map[string]int32 {
	return EventType_Enum_value
}

// NamesMap returns map of enum names
func (s EventType_Enum) NamesMap() map[int32]string {
	return EventType_Enum_name
}

// DisplayNamesMap returns a map of enum display names
func (s EventType_Enum) DisplayNamesMap() map[int32]string {
	return EventType_Enum_displayName
}

// SupportedNames returns string of supported Enum name concatenated by ","
func (s EventType_Enum) SupportedNames() string {
	return enum.SupportedNames[EventType_Enum]()
}

// ValueNames returns list of Enum value names
func (s EventType_Enum) ValueNames() []string {
	return enum.FlagNames(s)
}

// ValueString returns string of Enum value names concatenated by ","
func (s EventType_Enum) ValueString() string {
	return strings.Join(s.ValueNames(), ",")
}

// Flags returns list of Enum values
func (s EventType_Enum) Flags() []EventType_Enum {
	return enum.Flags(s)
}

// FlagsInt returns list of Enum values as int32
func (s EventType_Enum) FlagsInt() []int32 {
	return enum.FlagsInt(s)
}

// UnmarshalYAML unmarshals Enum from YAML
func (s *EventType_Enum) UnmarshalYAML(unmarshal func(any) error) error {
	// Try to unmarshal as an integer
	var valInt int32
	if err := unmarshal(&valInt); err == nil {
		*s = EventType_Enum(valInt)
		return nil
	}

	// Try to unmarshal as a string
	var valStr string
	if err := unmarshal(&valStr); err == nil {
		*s = enum.Parse[EventType_Enum](valStr)
		return nil
	}

	// If both attempts fail, set to default
	*s = 0
	return nil
}

// UnmarshalJSON unmarshals Enum from JSON
func (s *EventType_Enum) UnmarshalJSON(b []byte) error {
	var val any
	if err := json.Unmarshal(b, &val); err != nil {
		return err
	}
	*s = EventType_Enum(0).Parse(val)
	return nil
}

// DisplayNames returns display names of Enum bitflag value
func (s EventType_Enum) DisplayNames() []string {
	flags := enum.Flags(s)
	count := len(flags)
	if count == 0 {
		return []string{s.String()}
	}
	if count == 1 {
		return []string{EventType_Enum_DisplayName[flags[0]]}
	}
	var names []string
	for _, flag := range flags {
		names = append(names, EventType_Enum_DisplayName[flag])
	}
	return names
}

// DisplayName returns display name of Enum value
func (s EventType_Enum) DisplayName() string {
	if val, ok := EventType_Enum_DisplayName[s]; ok {
		return val
	}
	return s.String()
}

// Meta returns Enum meta information
func (s EventType_Enum) Meta() *api.EnumMeta {
	return EventType_Enum_Meta[s]
}

// Describe returns Enum meta information for all values
func (s EventType_Enum) Describe() map[EventType_Enum]*api.EnumMeta {
	return EventType_Enum_Meta
}

// GetDescription returns Enum description
func (s EventType_Enum) GetDescription() *api.EnumDescription {
	return EventType_Enum_EnumDescription
}

// Parse returns Enum value parsed from val
func (_ EventType_Enum) Parse(val any) EventType_Enum {
	return EventType_Enum_EnumDescription.ParseEnum[EventType_Enum](val)
}

var EventType_Enum_Name = map[EventType_Enum]string{
	EventType_Unknown:              "Unknown",
	EventType_OrgCreated:           "OrgCreated",
	EventType_OrgUpdated:           "OrgUpdated",
	EventType_OrgDeleted:           "OrgDeleted",
	EventType_OrgMemberAdded:       "OrgMemberAdded",
	EventType_OrgMemberRemoved:     "OrgMemberRemoved",
	EventType_OrgMemberRoleChanged: "OrgMemberRoleChanged",
	EventType_OrgMemberInvited:     "OrgMemberInvited",
	EventType_OrgMemberAccepted:    "OrgMemberAccepted",
}

var EventType_Enum_Value = map[string]EventType_Enum{
	"Unknown":              EventType_Unknown,
	"OrgCreated":           EventType_OrgCreated,
	"OrgUpdated":           EventType_OrgUpdated,
	"OrgDeleted":           EventType_OrgDeleted,
	"OrgMemberAdded":       EventType_OrgMemberAdded,
	"OrgMemberRemoved":     EventType_OrgMemberRemoved,
	"OrgMemberRoleChanged": EventType_OrgMemberRoleChanged,
	"OrgMemberInvited":     EventType_OrgMemberInvited,
	"OrgMemberAccepted":    EventType_OrgMemberAccepted,
}

var EventType_Enum_DisplayName = map[EventType_Enum]string{
	EventType_Unknown:              Display_EventType_Unknown,
	EventType_OrgCreated:           Display_EventType_OrgCreated,
	EventType_OrgUpdated:           Display_EventType_OrgUpdated,
	EventType_OrgDeleted:           Display_EventType_OrgDeleted,
	EventType_OrgMemberAdded:       Display_EventType_OrgMemberAdded,
	EventType_OrgMemberRemoved:     Display_EventType_OrgMemberRemoved,
	EventType_OrgMemberRoleChanged: Display_EventType_OrgMemberRoleChanged,
	EventType_OrgMemberInvited:     Display_EventType_OrgMemberInvited,
	EventType_OrgMemberAccepted:    Display_EventType_OrgMemberAccepted,
}

var EventType_Enum_displayName = map[int32]string{
	0: Display_EventType_Unknown,
	1: Display_EventType_OrgCreated,
	2: Display_EventType_OrgUpdated,
	3: Display_EventType_OrgDeleted,
	4: Display_EventType_OrgMemberAdded,
	5: Display_EventType_OrgMemberRemoved,
	6: Display_EventType_OrgMemberRoleChanged,
	7: Display_EventType_OrgMemberInvited,
	8: Display_EventType_OrgMemberAccepted,
}

var EventType_Enum_EnumDescription = &api.EnumDescription{
	Name:      "EventType_Enum",
	FullName:  "pb.EventType.Enum",
	IsBitmask: false,
	Enums: []*api.EnumMeta{
		{
			Value:         0,
			Name:          "Unknown",
			FullName:      "pb.EventType.Unknown",
			Display:       Display_EventType_Unknown,
			Documentation: `Unknown indicates that the event type is unknown`,
		},
		{
			Value:         1,
			Name:          "OrgCreated",
			FullName:      "pb.EventType.OrgCreated",
			Display:       Display_EventType_OrgCreated,
			Documentation: `OrgCreated indicates that an org was created`,
		},
		{
			Value:         2,
			Name:          "OrgUpdated",
			FullName:      "pb.EventType.OrgUpdated",
			Display:       Display_EventType_OrgUpdated,
			Documentation: `OrgUpdated indicates that an org was updated`,
		},
		{
			Value:         3,
			Name:          "OrgDeleted",
			FullName:      "pb.EventType.OrgDeleted",
			Display:       Display_EventType_OrgDeleted,
			Documentation: `OrgDeleted indicates that an org was deleted`,
		},
		{
			Value:         4,
			Name:          "OrgMemberAdded",
			FullName:      "pb.EventType.OrgMemberAdded",
			Display:       Display_EventType_OrgMemberAdded,
			Documentation: `OrgMemberAdded indicates that an org member was added`,
		},
		{
			Value:         5,
			Name:          "OrgMemberRemoved",
			FullName:      "pb.EventType.OrgMemberRemoved",
			Display:       Display_EventType_OrgMemberRemoved,
			Documentation: `OrgMemberRemoved indicates that an org member was removed`,
		},
		{
			Value:    6,
			Name:     "OrgMemberRoleChanged",
			FullName: "pb.EventType.OrgMemberRoleChanged",
			Display:  Display_EventType_OrgMemberRoleChanged,
			Documentation: `OrgMemberRoleChanged indicates that an org member role was
changed`,
		},
		{
			Value:         7,
			Name:          "OrgMemberInvited",
			FullName:      "pb.EventType.OrgMemberInvited",
			Display:       Display_EventType_OrgMemberInvited,
			Documentation: `OrgMemberInvited indicates that an org member was invited`,
		},
		{
			Value:    8,
			Name:     "OrgMemberAccepted",
			FullName: "pb.EventType.OrgMemberAccepted",
			Display:  Display_EventType_OrgMemberAccepted,
			Documentation: `OrgMemberAccepted indicates that an org member accepted an
invitation`,
		},
	},
	Documentation: `EventType defines event types`,
}

var EventType_Enum_Meta = map[EventType_Enum]*api.EnumMeta{
	EventType_Unknown:              EventType_Enum_EnumDescription.Enums[0],
	EventType_OrgCreated:           EventType_Enum_EnumDescription.Enums[1],
	EventType_OrgUpdated:           EventType_Enum_EnumDescription.Enums[2],
	EventType_OrgDeleted:           EventType_Enum_EnumDescription.Enums[3],
	EventType_OrgMemberAdded:       EventType_Enum_EnumDescription.Enums[4],
	EventType_OrgMemberRemoved:     EventType_Enum_EnumDescription.Enums[5],
	EventType_OrgMemberRoleChanged: EventType_Enum_EnumDescription.Enums[6],
	EventType_OrgMemberInvited:     EventType_Enum_EnumDescription.Enums[7],
	EventType_OrgMemberAccepted:    EventType_Enum_EnumDescription.Enums[8],
}

//
// IDP_Enum
//

type IDP_EnumSlice []IDP_Enum

const IDP_Enum_SupportedNamesHelp = "Undefined,Google,Github,Gitlab,Local"

// ValuesMap returns a map of enum values
func (s IDP_Enum) ValuesMap() map[string]int32 {
	return IDP_Enum_value
}

// NamesMap returns map of enum names
func (s IDP_Enum) NamesMap() map[int32]string {
	return IDP_Enum_name
}

// DisplayNamesMap returns a map of enum display names
func (s IDP_Enum) DisplayNamesMap() map[int32]string {
	return IDP_Enum_displayName
}

// SupportedNames returns string of supported Enum name concatenated by ","
func (s IDP_Enum) SupportedNames() string {
	return enum.SupportedNames[IDP_Enum]()
}

// ValueNames returns list of Enum value names
func (s IDP_Enum) ValueNames() []string {
	return enum.FlagNames(s)
}

// ValueString returns string of Enum value names concatenated by ","
func (s IDP_Enum) ValueString() string {
	return strings.Join(s.ValueNames(), ",")
}

// Flags returns list of Enum values
func (s IDP_Enum) Flags() []IDP_Enum {
	return enum.Flags(s)
}

// FlagsInt returns list of Enum values as int32
func (s IDP_Enum) FlagsInt() []int32 {
	return enum.FlagsInt(s)
}

// UnmarshalYAML unmarshals Enum from YAML
func (s *IDP_Enum) UnmarshalYAML(unmarshal func(any) error) error {
	// Try to unmarshal as an integer
	var valInt int32
	if err := unmarshal(&valInt); err == nil {
		*s = IDP_Enum(valInt)
		return nil
	}

	// Try to unmarshal as a string
	var valStr string
	if err := unmarshal(&valStr); err == nil {
		*s = enum.Parse[IDP_Enum](valStr)
		return nil
	}

	// If both attempts fail, set to default
	*s = 0
	return nil
}

// UnmarshalJSON unmarshals Enum from JSON
func (s *IDP_Enum) UnmarshalJSON(b []byte) error {
	var val any
	if err := json.Unmarshal(b, &val); err != nil {
		return err
	}
	*s = IDP_Enum(0).Parse(val)
	return nil
}

// DisplayNames returns display names of Enum bitflag value
func (s IDP_Enum) DisplayNames() []string {
	flags := enum.Flags(s)
	count := len(flags)
	if count == 0 {
		return []string{s.String()}
	}
	if count == 1 {
		return []string{IDP_Enum_DisplayName[flags[0]]}
	}
	var names []string
	for _, flag := range flags {
		names = append(names, IDP_Enum_DisplayName[flag])
	}
	return names
}

// DisplayName returns display name of Enum value
func (s IDP_Enum) DisplayName() string {
	if val, ok := IDP_Enum_DisplayName[s]; ok {
		return val
	}
	return s.String()
}

// Meta returns Enum meta information
func (s IDP_Enum) Meta() *api.EnumMeta {
	return IDP_Enum_Meta[s]
}

// Describe returns Enum meta information for all values
func (s IDP_Enum) Describe() map[IDP_Enum]*api.EnumMeta {
	return IDP_Enum_Meta
}

// GetDescription returns Enum description
func (s IDP_Enum) GetDescription() *api.EnumDescription {
	return IDP_Enum_EnumDescription
}

// Parse returns Enum value parsed from val
func (_ IDP_Enum) Parse(val any) IDP_Enum {
	return IDP_Enum_EnumDescription.ParseEnum[IDP_Enum](val)
}

var IDP_Enum_Name = map[IDP_Enum]string{
	IDP_Undefined: "Undefined",
	IDP_Google:    "Google",
	IDP_Github:    "Github",
	IDP_Gitlab:    "Gitlab",
	IDP_Local:     "Local",
}

var IDP_Enum_Value = map[string]IDP_Enum{
	"Undefined": IDP_Undefined,
	"Google":    IDP_Google,
	"Github":    IDP_Github,
	"Gitlab":    IDP_Gitlab,
	"Local":     IDP_Local,
}

var IDP_Enum_DisplayName = map[IDP_Enum]string{
	IDP_Undefined: Display_IDP_Undefined,
	IDP_Google:    Display_IDP_Google,
	IDP_Github:    Display_IDP_Github,
	IDP_Gitlab:    Display_IDP_Gitlab,
	IDP_Local:     Display_IDP_Local,
}

var IDP_Enum_displayName = map[int32]string{
	0:    Display_IDP_Undefined,
	1:    Display_IDP_Google,
	2:    Display_IDP_Github,
	3:    Display_IDP_Gitlab,
	1000: Display_IDP_Local,
}

var IDP_Enum_EnumDescription = &api.EnumDescription{
	Name:      "IDP_Enum",
	FullName:  "pb.IDP.Enum",
	IsBitmask: false,
	Enums: []*api.EnumMeta{
		{
			Value:         0,
			Name:          "Undefined",
			FullName:      "pb.IDP.Undefined",
			Display:       Display_IDP_Undefined,
			Documentation: `Undefined indicates that the IDP is undefined`,
		},
		{
			Value:         1,
			Name:          "Google",
			FullName:      "pb.IDP.Google",
			Display:       Display_IDP_Google,
			Documentation: `Google indicates that the IDP is Google`,
		},
		{
			Value:         2,
			Name:          "Github",
			FullName:      "pb.IDP.Github",
			Display:       Display_IDP_Github,
			Documentation: `Github indicates that the IDP is Github`,
		},
		{
			Value:         3,
			Name:          "Gitlab",
			FullName:      "pb.IDP.Gitlab",
			Display:       Display_IDP_Gitlab,
			Documentation: `Gitlab indicates that the IDP is Gitlab`,
		},
		{
			Value:         1000,
			Name:          "Local",
			FullName:      "pb.IDP.Local",
			Display:       Display_IDP_Local,
			Documentation: `Local indicates that the IDP is local for testing`,
		},
	},
}

var IDP_Enum_Meta = map[IDP_Enum]*api.EnumMeta{
	IDP_Undefined: IDP_Enum_EnumDescription.Enums[0],
	IDP_Google:    IDP_Enum_EnumDescription.Enums[1],
	IDP_Github:    IDP_Enum_EnumDescription.Enums[2],
	IDP_Gitlab:    IDP_Enum_EnumDescription.Enums[3],
	IDP_Local:     IDP_Enum_EnumDescription.Enums[4],
}

//
// ItemStatus_Enum
//

type ItemStatus_EnumSlice []ItemStatus_Enum

const ItemStatus_Enum_SupportedNamesHelp = "Unknown,Inactive,Active,Invalid"

// ValuesMap returns a map of enum values
func (s ItemStatus_Enum) ValuesMap() map[string]int32 {
	return ItemStatus_Enum_value
}

// NamesMap returns map of enum names
func (s ItemStatus_Enum) NamesMap() map[int32]string {
	return ItemStatus_Enum_name
}

// DisplayNamesMap returns a map of enum display names
func (s ItemStatus_Enum) DisplayNamesMap() map[int32]string {
	return ItemStatus_Enum_displayName
}

// SupportedNames returns string of supported Enum name concatenated by ","
func (s ItemStatus_Enum) SupportedNames() string {
	return enum.SupportedNames[ItemStatus_Enum]()
}

// ValueNames returns list of Enum value names
func (s ItemStatus_Enum) ValueNames() []string {
	return enum.FlagNames(s)
}

// ValueString returns string of Enum value names concatenated by ","
func (s ItemStatus_Enum) ValueString() string {
	return strings.Join(s.ValueNames(), ",")
}

// Flags returns list of Enum values
func (s ItemStatus_Enum) Flags() []ItemStatus_Enum {
	return enum.Flags(s)
}

// FlagsInt returns list of Enum values as int32
func (s ItemStatus_Enum) FlagsInt() []int32 {
	return enum.FlagsInt(s)
}

// UnmarshalYAML unmarshals Enum from YAML
func (s *ItemStatus_Enum) UnmarshalYAML(unmarshal func(any) error) error {
	// Try to unmarshal as an integer
	var valInt int32
	if err := unmarshal(&valInt); err == nil {
		*s = ItemStatus_Enum(valInt)
		return nil
	}

	// Try to unmarshal as a string
	var valStr string
	if err := unmarshal(&valStr); err == nil {
		*s = enum.Parse[ItemStatus_Enum](valStr)
		return nil
	}

	// If both attempts fail, set to default
	*s = 0
	return nil
}

// UnmarshalJSON unmarshals Enum from JSON
func (s *ItemStatus_Enum) UnmarshalJSON(b []byte) error {
	var val any
	if err := json.Unmarshal(b, &val); err != nil {
		return err
	}
	*s = ItemStatus_Enum(0).Parse(val)
	return nil
}

// DisplayNames returns display names of Enum bitflag value
func (s ItemStatus_Enum) DisplayNames() []string {
	flags := enum.Flags(s)
	count := len(flags)
	if count == 0 {
		return []string{s.String()}
	}
	if count == 1 {
		return []string{ItemStatus_Enum_DisplayName[flags[0]]}
	}
	var names []string
	for _, flag := range flags {
		names = append(names, ItemStatus_Enum_DisplayName[flag])
	}
	return names
}

// DisplayName returns display name of Enum value
func (s ItemStatus_Enum) DisplayName() string {
	if val, ok := ItemStatus_Enum_DisplayName[s]; ok {
		return val
	}
	return s.String()
}

// Meta returns Enum meta information
func (s ItemStatus_Enum) Meta() *api.EnumMeta {
	return ItemStatus_Enum_Meta[s]
}

// Describe returns Enum meta information for all values
func (s ItemStatus_Enum) Describe() map[ItemStatus_Enum]*api.EnumMeta {
	return ItemStatus_Enum_Meta
}

// GetDescription returns Enum description
func (s ItemStatus_Enum) GetDescription() *api.EnumDescription {
	return ItemStatus_Enum_EnumDescription
}

// Parse returns Enum value parsed from val
func (_ ItemStatus_Enum) Parse(val any) ItemStatus_Enum {
	return ItemStatus_Enum_EnumDescription.ParseEnum[ItemStatus_Enum](val)
}

var ItemStatus_Enum_Name = map[ItemStatus_Enum]string{
	ItemStatus_Unknown:  "Unknown",
	ItemStatus_Inactive: "Inactive",
	ItemStatus_Active:   "Active",
	ItemStatus_Invalid:  "Invalid",
}

var ItemStatus_Enum_Value = map[string]ItemStatus_Enum{
	"Unknown":  ItemStatus_Unknown,
	"Inactive": ItemStatus_Inactive,
	"Active":   ItemStatus_Active,
	"Invalid":  ItemStatus_Invalid,
}

var ItemStatus_Enum_DisplayName = map[ItemStatus_Enum]string{
	ItemStatus_Unknown:  Display_ItemStatus_Unknown,
	ItemStatus_Inactive: Display_ItemStatus_Inactive,
	ItemStatus_Active:   Display_ItemStatus_Active,
	ItemStatus_Invalid:  Display_ItemStatus_Invalid,
}

var ItemStatus_Enum_displayName = map[int32]string{
	0: Display_ItemStatus_Unknown,
	1: Display_ItemStatus_Inactive,
	2: Display_ItemStatus_Active,
	4: Display_ItemStatus_Invalid,
}

var ItemStatus_Enum_EnumDescription = &api.EnumDescription{
	Name:      "ItemStatus_Enum",
	FullName:  "pb.ItemStatus.Enum",
	IsBitmask: false,
	Enums: []*api.EnumMeta{
		{
			Value:         0,
			Name:          "Unknown",
			FullName:      "pb.ItemStatus.Unknown",
			Display:       Display_ItemStatus_Unknown,
			Documentation: `Unknown indicates that the status is unknown`,
		},
		{
			Value:         1,
			Name:          "Inactive",
			FullName:      "pb.ItemStatus.Inactive",
			Display:       Display_ItemStatus_Inactive,
			Documentation: `Inactive indicates that the item is inactive or pending deletion`,
		},
		{
			Value:         2,
			Name:          "Active",
			FullName:      "pb.ItemStatus.Active",
			Display:       Display_ItemStatus_Active,
			Documentation: `Active indicates that the item is active and ready to use`,
		},
		{
			Value:    4,
			Name:     "Invalid",
			FullName: "pb.ItemStatus.Invalid",
			Display:  Display_ItemStatus_Invalid,
			Documentation: `Invalid indicates that the item is invalid and needs an action to be
taken`,
		},
	},
	Documentation: `ItemStatus defines status constants for items`,
}

var ItemStatus_Enum_Meta = map[ItemStatus_Enum]*api.EnumMeta{
	ItemStatus_Unknown:  ItemStatus_Enum_EnumDescription.Enums[0],
	ItemStatus_Inactive: ItemStatus_Enum_EnumDescription.Enums[1],
	ItemStatus_Active:   ItemStatus_Enum_EnumDescription.Enums[2],
	ItemStatus_Invalid:  ItemStatus_Enum_EnumDescription.Enums[3],
}

//
// PermissionsScope_Enum
//

type PermissionsScope_EnumSlice []PermissionsScope_Enum

const PermissionsScope_Enum_SupportedNamesHelp = "None,ReadOnly,Restricted,All"

// ValuesMap returns a map of enum values
func (s PermissionsScope_Enum) ValuesMap() map[string]int32 {
	return PermissionsScope_Enum_value
}

// NamesMap returns map of enum names
func (s PermissionsScope_Enum) NamesMap() map[int32]string {
	return PermissionsScope_Enum_name
}

// DisplayNamesMap returns a map of enum display names
func (s PermissionsScope_Enum) DisplayNamesMap() map[int32]string {
	return PermissionsScope_Enum_displayName
}

// SupportedNames returns string of supported Enum name concatenated by ","
func (s PermissionsScope_Enum) SupportedNames() string {
	return enum.SupportedNames[PermissionsScope_Enum]()
}

// ValueNames returns list of Enum value names
func (s PermissionsScope_Enum) ValueNames() []string {
	return enum.FlagNames(s)
}

// ValueString returns string of Enum value names concatenated by ","
func (s PermissionsScope_Enum) ValueString() string {
	return strings.Join(s.ValueNames(), ",")
}

// Flags returns list of Enum values
func (s PermissionsScope_Enum) Flags() []PermissionsScope_Enum {
	return enum.Flags(s)
}

// FlagsInt returns list of Enum values as int32
func (s PermissionsScope_Enum) FlagsInt() []int32 {
	return enum.FlagsInt(s)
}

// UnmarshalYAML unmarshals Enum from YAML
func (s *PermissionsScope_Enum) UnmarshalYAML(unmarshal func(any) error) error {
	// Try to unmarshal as an integer
	var valInt int32
	if err := unmarshal(&valInt); err == nil {
		*s = PermissionsScope_Enum(valInt)
		return nil
	}

	// Try to unmarshal as a string
	var valStr string
	if err := unmarshal(&valStr); err == nil {
		*s = enum.Parse[PermissionsScope_Enum](valStr)
		return nil
	}

	// If both attempts fail, set to default
	*s = 0
	return nil
}

// UnmarshalJSON unmarshals Enum from JSON
func (s *PermissionsScope_Enum) UnmarshalJSON(b []byte) error {
	var val any
	if err := json.Unmarshal(b, &val); err != nil {
		return err
	}
	*s = PermissionsScope_Enum(0).Parse(val)
	return nil
}

// DisplayNames returns display names of Enum bitflag value
func (s PermissionsScope_Enum) DisplayNames() []string {
	flags := enum.Flags(s)
	count := len(flags)
	if count == 0 {
		return []string{s.String()}
	}
	if count == 1 {
		return []string{PermissionsScope_Enum_DisplayName[flags[0]]}
	}
	var names []string
	for _, flag := range flags {
		names = append(names, PermissionsScope_Enum_DisplayName[flag])
	}
	return names
}

// DisplayName returns display name of Enum value
func (s PermissionsScope_Enum) DisplayName() string {
	flags := enum.Flags(s)
	count := len(flags)
	if count == 0 {
		return s.String()
	}
	if count == 1 {
		return PermissionsScope_Enum_DisplayName[flags[0]]
	}
	var names []string
	for _, flag := range flags {
		names = append(names, PermissionsScope_Enum_DisplayName[flag])
	}
	return strings.Join(names, ",")
}

// Meta returns Enum meta information
func (s PermissionsScope_Enum) Meta() *api.EnumMeta {
	return PermissionsScope_Enum_Meta[s]
}

// Describe returns Enum meta information for all values
func (s PermissionsScope_Enum) Describe() map[PermissionsScope_Enum]*api.EnumMeta {
	return PermissionsScope_Enum_Meta
}

// GetDescription returns Enum description
func (s PermissionsScope_Enum) GetDescription() *api.EnumDescription {
	return PermissionsScope_Enum_EnumDescription
}

// Parse returns Enum value parsed from val
func (_ PermissionsScope_Enum) Parse(val any) PermissionsScope_Enum {
	return PermissionsScope_Enum_EnumDescription.ParseEnum[PermissionsScope_Enum](val)
}

var PermissionsScope_Enum_Name = map[PermissionsScope_Enum]string{
	PermissionsScope_None:       "None",
	PermissionsScope_ReadOnly:   "ReadOnly",
	PermissionsScope_Restricted: "Restricted",
	PermissionsScope_All:        "All",
}

var PermissionsScope_Enum_Value = map[string]PermissionsScope_Enum{
	"None":       PermissionsScope_None,
	"ReadOnly":   PermissionsScope_ReadOnly,
	"Restricted": PermissionsScope_Restricted,
	"All":        PermissionsScope_All,
}

var PermissionsScope_Enum_DisplayName = map[PermissionsScope_Enum]string{
	PermissionsScope_None:       Display_PermissionsScope_None,
	PermissionsScope_ReadOnly:   Display_PermissionsScope_ReadOnly,
	PermissionsScope_Restricted: Display_PermissionsScope_Restricted,
	PermissionsScope_All:        Display_PermissionsScope_All,
}

var PermissionsScope_Enum_displayName = map[int32]string{
	0:          Display_PermissionsScope_None,
	1:          Display_PermissionsScope_ReadOnly,
	2:          Display_PermissionsScope_Restricted,
	2147483647: Display_PermissionsScope_All,
}

var PermissionsScope_Enum_EnumDescription = &api.EnumDescription{
	Name:      "PermissionsScope_Enum",
	FullName:  "pb.PermissionsScope.Enum",
	IsBitmask: true,
	Enums: []*api.EnumMeta{
		{
			Value:         0,
			Name:          "None",
			FullName:      "pb.PermissionsScope.None",
			Display:       Display_PermissionsScope_None,
			Documentation: `None indicates that the permissions scope is none`,
		},
		{
			Value:         1,
			Name:          "ReadOnly",
			FullName:      "pb.PermissionsScope.ReadOnly",
			Display:       Display_PermissionsScope_ReadOnly,
			Documentation: `ReadOnly indicates that the permissions scope is read only`,
		},
		{
			Value:         2,
			Name:          "Restricted",
			FullName:      "pb.PermissionsScope.Restricted",
			Display:       Display_PermissionsScope_Restricted,
			Documentation: `Restricted indicates that the permissions scope is restricted`,
		},
		{
			Value:         2147483647,
			Name:          "All",
			FullName:      "pb.PermissionsScope.All",
			Display:       Display_PermissionsScope_All,
			Documentation: `All is the bitmask for all permissions scopes`,
		},
	},
	Documentation: `PermissionsScope defines virtual key scopes`,
}

var PermissionsScope_Enum_Meta = map[PermissionsScope_Enum]*api.EnumMeta{
	PermissionsScope_None:       PermissionsScope_Enum_EnumDescription.Enums[0],
	PermissionsScope_ReadOnly:   PermissionsScope_Enum_EnumDescription.Enums[1],
	PermissionsScope_Restricted: PermissionsScope_Enum_EnumDescription.Enums[2],
	PermissionsScope_All:        PermissionsScope_Enum_EnumDescription.Enums[3],
}

//
// Role_Enum
//

type Role_EnumSlice []Role_Enum

const Role_Enum_SupportedNamesHelp = "None,APIKey,User,Support,Admin,Owner"

// ValuesMap returns a map of enum values
func (s Role_Enum) ValuesMap() map[string]int32 {
	return Role_Enum_value
}

// NamesMap returns map of enum names
func (s Role_Enum) NamesMap() map[int32]string {
	return Role_Enum_name
}

// DisplayNamesMap returns a map of enum display names
func (s Role_Enum) DisplayNamesMap() map[int32]string {
	return Role_Enum_displayName
}

// SupportedNames returns string of supported Enum name concatenated by ","
func (s Role_Enum) SupportedNames() string {
	return enum.SupportedNames[Role_Enum]()
}

// ValueNames returns list of Enum value names
func (s Role_Enum) ValueNames() []string {
	return enum.FlagNames(s)
}

// ValueString returns string of Enum value names concatenated by ","
func (s Role_Enum) ValueString() string {
	return strings.Join(s.ValueNames(), ",")
}

// Flags returns list of Enum values
func (s Role_Enum) Flags() []Role_Enum {
	return enum.Flags(s)
}

// FlagsInt returns list of Enum values as int32
func (s Role_Enum) FlagsInt() []int32 {
	return enum.FlagsInt(s)
}

// UnmarshalYAML unmarshals Enum from YAML
func (s *Role_Enum) UnmarshalYAML(unmarshal func(any) error) error {
	// Try to unmarshal as an integer
	var valInt int32
	if err := unmarshal(&valInt); err == nil {
		*s = Role_Enum(valInt)
		return nil
	}

	// Try to unmarshal as a string
	var valStr string
	if err := unmarshal(&valStr); err == nil {
		*s = enum.Parse[Role_Enum](valStr)
		return nil
	}

	// If both attempts fail, set to default
	*s = 0
	return nil
}

// UnmarshalJSON unmarshals Enum from JSON
func (s *Role_Enum) UnmarshalJSON(b []byte) error {
	var val any
	if err := json.Unmarshal(b, &val); err != nil {
		return err
	}
	*s = Role_Enum(0).Parse(val)
	return nil
}

// DisplayNames returns display names of Enum bitflag value
func (s Role_Enum) DisplayNames() []string {
	flags := enum.Flags(s)
	count := len(flags)
	if count == 0 {
		return []string{s.String()}
	}
	if count == 1 {
		return []string{Role_Enum_DisplayName[flags[0]]}
	}
	var names []string
	for _, flag := range flags {
		names = append(names, Role_Enum_DisplayName[flag])
	}
	return names
}

// DisplayName returns display name of Enum value
func (s Role_Enum) DisplayName() string {
	if val, ok := Role_Enum_DisplayName[s]; ok {
		return val
	}
	return s.String()
}

// Meta returns Enum meta information
func (s Role_Enum) Meta() *api.EnumMeta {
	return Role_Enum_Meta[s]
}

// Describe returns Enum meta information for all values
func (s Role_Enum) Describe() map[Role_Enum]*api.EnumMeta {
	return Role_Enum_Meta
}

// GetDescription returns Enum description
func (s Role_Enum) GetDescription() *api.EnumDescription {
	return Role_Enum_EnumDescription
}

// Parse returns Enum value parsed from val
func (_ Role_Enum) Parse(val any) Role_Enum {
	return Role_Enum_EnumDescription.ParseEnum[Role_Enum](val)
}

var Role_Enum_Name = map[Role_Enum]string{
	Role_None:    "None",
	Role_APIKey:  "APIKey",
	Role_User:    "User",
	Role_Support: "Support",
	Role_Admin:   "Admin",
	Role_Owner:   "Owner",
}

var Role_Enum_Value = map[string]Role_Enum{
	"None":    Role_None,
	"APIKey":  Role_APIKey,
	"User":    Role_User,
	"Support": Role_Support,
	"Admin":   Role_Admin,
	"Owner":   Role_Owner,
}

var Role_Enum_DisplayName = map[Role_Enum]string{
	Role_None:    Display_Role_None,
	Role_APIKey:  Display_Role_APIKey,
	Role_User:    Display_Role_User,
	Role_Support: Display_Role_Support,
	Role_Admin:   Display_Role_Admin,
	Role_Owner:   Display_Role_Owner,
}

var Role_Enum_displayName = map[int32]string{
	0: Display_Role_None,
	1: Display_Role_APIKey,
	2: Display_Role_User,
	3: Display_Role_Support,
	4: Display_Role_Admin,
	5: Display_Role_Owner,
}

var Role_Enum_EnumDescription = &api.EnumDescription{
	Name:      "Role_Enum",
	FullName:  "pb.Role.Enum",
	IsBitmask: false,
	Enums: []*api.EnumMeta{
		{
			Value:         0,
			Name:          "None",
			FullName:      "pb.Role.None",
			Display:       Display_Role_None,
			Documentation: `None specifies no role`,
		},
		{
			Value:    1,
			Name:     "APIKey",
			FullName: "pb.Role.APIKey",
			Display:  Display_Role_APIKey,
		},
		{
			Value:         2,
			Name:          "User",
			FullName:      "pb.Role.User",
			Display:       Display_Role_User,
			Documentation: `User specifies name for User role`,
		},
		{
			Value:         3,
			Name:          "Support",
			FullName:      "pb.Role.Support",
			Display:       Display_Role_Support,
			Documentation: `Support specifies name for Support role`,
		},
		{
			Value:         4,
			Name:          "Admin",
			FullName:      "pb.Role.Admin",
			Display:       Display_Role_Admin,
			Documentation: `Admin specifies name for Admin role`,
		},
		{
			Value:         5,
			Name:          "Owner",
			FullName:      "pb.Role.Owner",
			Display:       Display_Role_Owner,
			Documentation: `Owner specifies name for Owner role`,
		},
	},
}

var Role_Enum_Meta = map[Role_Enum]*api.EnumMeta{
	Role_None:    Role_Enum_EnumDescription.Enums[0],
	Role_APIKey:  Role_Enum_EnumDescription.Enums[1],
	Role_User:    Role_Enum_EnumDescription.Enums[2],
	Role_Support: Role_Enum_EnumDescription.Enums[3],
	Role_Admin:   Role_Enum_EnumDescription.Enums[4],
	Role_Owner:   Role_Enum_EnumDescription.Enums[5],
}
