// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: orgs.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orgs_RegisterOrg_FullMethodName        = "/pb.Orgs/RegisterOrg"
	Orgs_UpdateOrg_FullMethodName          = "/pb.Orgs/UpdateOrg"
	Orgs_GetOrg_FullMethodName             = "/pb.Orgs/GetOrg"
	Orgs_DeleteOrg_FullMethodName          = "/pb.Orgs/DeleteOrg"
	Orgs_GetUserMemberships_FullMethodName = "/pb.Orgs/GetUserMemberships"
	Orgs_GetMembers_FullMethodName         = "/pb.Orgs/GetMembers"
	Orgs_AddMember_FullMethodName          = "/pb.Orgs/AddMember"
	Orgs_ChangeMemberRole_FullMethodName   = "/pb.Orgs/ChangeMemberRole"
	Orgs_DeleteMember_FullMethodName       = "/pb.Orgs/DeleteMember"
	Orgs_DeleteInvite_FullMethodName       = "/pb.Orgs/DeleteInvite"
)

// OrgsClient is the client API for Orgs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrgsClient interface {
	// RegisterOrg registers a new org
	RegisterOrg(ctx context.Context, in *RegisterOrgRequest, opts ...grpc.CallOption) (*Org, error)
	// UpdateOrg updates an org
	UpdateOrg(ctx context.Context, in *UpdateOrgRequest, opts ...grpc.CallOption) (*Org, error)
	// GetOrg returns an org by ID
	GetOrg(ctx context.Context, in *GetOrgRequest, opts ...grpc.CallOption) (*Org, error)
	// DeleteProject deletes a project
	DeleteOrg(ctx context.Context, in *DeleteOrgRequest, opts ...grpc.CallOption) (*Org, error)
	// GetUserMemberships returns list of calling user orgs
	GetUserMemberships(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserMemberships, error)
	// GetMembers returns list of membership info for the org by org ID
	GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*MembersResponse, error)
	// AddMember adds a user to Org
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error)
	// ChangeMemberRole changes user role
	ChangeMemberRole(ctx context.Context, in *ChangeMemberRoleRequest, opts ...grpc.CallOption) (*Membership, error)
	// DeleteMember removes user from the project
	DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteInvite removes user invite
	DeleteInvite(ctx context.Context, in *DeleteInviteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type orgsClient struct {
	cc grpc.ClientConnInterface
}

func NewOrgsClient(cc grpc.ClientConnInterface) OrgsClient {
	return &orgsClient{cc}
}

func (c *orgsClient) RegisterOrg(ctx context.Context, in *RegisterOrgRequest, opts ...grpc.CallOption) (*Org, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Org)
	err := c.cc.Invoke(ctx, Orgs_RegisterOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) UpdateOrg(ctx context.Context, in *UpdateOrgRequest, opts ...grpc.CallOption) (*Org, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Org)
	err := c.cc.Invoke(ctx, Orgs_UpdateOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) GetOrg(ctx context.Context, in *GetOrgRequest, opts ...grpc.CallOption) (*Org, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Org)
	err := c.cc.Invoke(ctx, Orgs_GetOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) DeleteOrg(ctx context.Context, in *DeleteOrgRequest, opts ...grpc.CallOption) (*Org, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Org)
	err := c.cc.Invoke(ctx, Orgs_DeleteOrg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) GetUserMemberships(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserMemberships, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserMemberships)
	err := c.cc.Invoke(ctx, Orgs_GetUserMemberships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*MembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembersResponse)
	err := c.cc.Invoke(ctx, Orgs_GetMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMemberResponse)
	err := c.cc.Invoke(ctx, Orgs_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) ChangeMemberRole(ctx context.Context, in *ChangeMemberRoleRequest, opts ...grpc.CallOption) (*Membership, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Membership)
	err := c.cc.Invoke(ctx, Orgs_ChangeMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) DeleteMember(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Orgs_DeleteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgsClient) DeleteInvite(ctx context.Context, in *DeleteInviteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Orgs_DeleteInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrgsServer is the server API for Orgs service.
// All implementations should embed UnimplementedOrgsServer
// for forward compatibility.
type OrgsServer interface {
	// RegisterOrg registers a new org
	RegisterOrg(context.Context, *RegisterOrgRequest) (*Org, error)
	// UpdateOrg updates an org
	UpdateOrg(context.Context, *UpdateOrgRequest) (*Org, error)
	// GetOrg returns an org by ID
	GetOrg(context.Context, *GetOrgRequest) (*Org, error)
	// DeleteProject deletes a project
	DeleteOrg(context.Context, *DeleteOrgRequest) (*Org, error)
	// GetUserMemberships returns list of calling user orgs
	GetUserMemberships(context.Context, *emptypb.Empty) (*UserMemberships, error)
	// GetMembers returns list of membership info for the org by org ID
	GetMembers(context.Context, *GetMembersRequest) (*MembersResponse, error)
	// AddMember adds a user to Org
	AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error)
	// ChangeMemberRole changes user role
	ChangeMemberRole(context.Context, *ChangeMemberRoleRequest) (*Membership, error)
	// DeleteMember removes user from the project
	DeleteMember(context.Context, *DeleteMemberRequest) (*emptypb.Empty, error)
	// DeleteInvite removes user invite
	DeleteInvite(context.Context, *DeleteInviteRequest) (*emptypb.Empty, error)
}

// UnimplementedOrgsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrgsServer struct{}

func (UnimplementedOrgsServer) RegisterOrg(context.Context, *RegisterOrgRequest) (*Org, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterOrg not implemented")
}
func (UnimplementedOrgsServer) UpdateOrg(context.Context, *UpdateOrgRequest) (*Org, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrg not implemented")
}
func (UnimplementedOrgsServer) GetOrg(context.Context, *GetOrgRequest) (*Org, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrg not implemented")
}
func (UnimplementedOrgsServer) DeleteOrg(context.Context, *DeleteOrgRequest) (*Org, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrg not implemented")
}
func (UnimplementedOrgsServer) GetUserMemberships(context.Context, *emptypb.Empty) (*UserMemberships, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMemberships not implemented")
}
func (UnimplementedOrgsServer) GetMembers(context.Context, *GetMembersRequest) (*MembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembers not implemented")
}
func (UnimplementedOrgsServer) AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedOrgsServer) ChangeMemberRole(context.Context, *ChangeMemberRoleRequest) (*Membership, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeMemberRole not implemented")
}
func (UnimplementedOrgsServer) DeleteMember(context.Context, *DeleteMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMember not implemented")
}
func (UnimplementedOrgsServer) DeleteInvite(context.Context, *DeleteInviteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInvite not implemented")
}
func (UnimplementedOrgsServer) testEmbeddedByValue() {}

// UnsafeOrgsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrgsServer will
// result in compilation errors.
type UnsafeOrgsServer interface {
	mustEmbedUnimplementedOrgsServer()
}

func RegisterOrgsServer(s grpc.ServiceRegistrar, srv OrgsServer) {
	// If the following call panics, it indicates UnimplementedOrgsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orgs_ServiceDesc, srv)
}

func _Orgs_RegisterOrg_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(RegisterOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).RegisterOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_RegisterOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).RegisterOrg(ctx, req.(*RegisterOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_UpdateOrg_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(UpdateOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).UpdateOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_UpdateOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).UpdateOrg(ctx, req.(*UpdateOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_GetOrg_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).GetOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_GetOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).GetOrg(ctx, req.(*GetOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_DeleteOrg_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(DeleteOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).DeleteOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_DeleteOrg_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).DeleteOrg(ctx, req.(*DeleteOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_GetUserMemberships_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).GetUserMemberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_GetUserMemberships_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).GetUserMemberships(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_GetMembers_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_GetMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).GetMembers(ctx, req.(*GetMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_AddMember_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_ChangeMemberRole_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ChangeMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).ChangeMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_ChangeMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).ChangeMemberRole(ctx, req.(*ChangeMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_DeleteMember_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(DeleteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_DeleteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).DeleteMember(ctx, req.(*DeleteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orgs_DeleteInvite_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(DeleteInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgsServer).DeleteInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orgs_DeleteInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(OrgsServer).DeleteInvite(ctx, req.(*DeleteInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orgs_ServiceDesc is the grpc.ServiceDesc for Orgs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orgs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Orgs",
	HandlerType: (*OrgsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterOrg",
			Handler:    _Orgs_RegisterOrg_Handler,
		},
		{
			MethodName: "UpdateOrg",
			Handler:    _Orgs_UpdateOrg_Handler,
		},
		{
			MethodName: "GetOrg",
			Handler:    _Orgs_GetOrg_Handler,
		},
		{
			MethodName: "DeleteOrg",
			Handler:    _Orgs_DeleteOrg_Handler,
		},
		{
			MethodName: "GetUserMemberships",
			Handler:    _Orgs_GetUserMemberships_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _Orgs_GetMembers_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _Orgs_AddMember_Handler,
		},
		{
			MethodName: "ChangeMemberRole",
			Handler:    _Orgs_ChangeMemberRole_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _Orgs_DeleteMember_Handler,
		},
		{
			MethodName: "DeleteInvite",
			Handler:    _Orgs_DeleteInvite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orgs.proto",
}
