// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: orgs.proto

package pb

// MarshalJSON implements json.Marshaler
func (msg *Role) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *Role) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RoleSource) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RoleSource) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *Org) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *Org) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *OrgsResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *OrgsResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *Project) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *Project) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ProjectsResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ProjectsResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *OrgAccess) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *OrgAccess) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UserOrgsResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UserOrgsResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *Membership) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *Membership) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *Invite) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *Invite) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *GetMembersRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *GetMembersRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *MembersResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *MembersResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UserMemberships) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UserMemberships) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *AddMemberRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *AddMemberRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *AddMemberResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *AddMemberResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ChangeMemberRoleRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ChangeMemberRoleRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *DeleteMemberRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *DeleteMemberRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *DeleteInviteRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *DeleteInviteRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RegisterOrgRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RegisterOrgRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UpdateOrgRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UpdateOrgRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RegisterProjectRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RegisterProjectRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UpdateProjectRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UpdateProjectRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *GetProjectRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *GetProjectRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ListProjectsRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ListProjectsRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *DeleteProjectRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *DeleteProjectRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *EventsResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *EventsResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *APIKey) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *APIKey) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *APIKeysResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *APIKeysResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *CreateAPIKeyRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *CreateAPIKeyRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ListAPIKeysRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ListAPIKeysRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *APIKeyRequest) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *APIKeyRequest) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}
