// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: status.proto

package pb

// MarshalJSON implements json.Marshaler
func (msg *ServerVersion) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ServerVersion) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ServerStatus) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ServerStatus) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ServerStatusResponse) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ServerStatusResponse) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}
