// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: status.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/effective-security/protoc-gen-go/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerVersion provides server build and runtime version
type ServerVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Build is the server build version.
	Build string `protobuf:"bytes,1,opt,name=Build,proto3" json:"Build,omitempty"`
	// Runtime is the runtime version.
	Runtime       string `protobuf:"bytes,2,opt,name=Runtime,proto3" json:"Runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerVersion) Reset() {
	*x = ServerVersion{}
	mi := &file_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerVersion) ProtoMessage() {}

func (x *ServerVersion) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerVersion.ProtoReflect.Descriptor instead.
func (*ServerVersion) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{0}
}

func (x *ServerVersion) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *ServerVersion) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

// ServerStatus provides server status information
type ServerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the server or application.
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Nodename is the human-readable name of the cluster member,
	// or empty for single host.
	Nodename string `protobuf:"bytes,2,opt,name=Nodename,proto3" json:"Nodename,omitempty"`
	// Hostname is operating system's host name.
	Hostname string `protobuf:"bytes,3,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	// ListenURLs is the list of URLs the service is listening on.
	ListenUrls []string `protobuf:"bytes,4,rep,name=ListenUrls,proto3" json:"ListenUrls,omitempty"`
	// StartedAt is the time in RFC3339 format.
	StartedAt     string `protobuf:"bytes,5,opt,name=StartedAt,proto3" json:"StartedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerStatus) GetNodename() string {
	if x != nil {
		return x.Nodename
	}
	return ""
}

func (x *ServerStatus) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServerStatus) GetListenUrls() []string {
	if x != nil {
		return x.ListenUrls
	}
	return nil
}

func (x *ServerStatus) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

// ServerStatusResponse returns status and version
type ServerStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status of the server.
	Status *ServerStatus `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	// Version of the server.
	Version       *ServerVersion    `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Pods          map[string]string `protobuf:"bytes,3,rep,name=Pods,proto3" json:"Pods,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusResponse) Reset() {
	*x = ServerStatusResponse{}
	mi := &file_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusResponse) ProtoMessage() {}

func (x *ServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_status_proto_rawDescGZIP(), []int{2}
}

func (x *ServerStatusResponse) GetStatus() *ServerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ServerStatusResponse) GetVersion() *ServerVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ServerStatusResponse) GetPods() map[string]string {
	if x != nil {
		return x.Pods
	}
	return nil
}

var File_status_proto protoreflect.FileDescriptor

const file_status_proto_rawDesc = "" +
	"\n" +
	"\fstatus.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18es/api/annotations.proto\"?\n" +
	"\rServerVersion\x12\x14\n" +
	"\x05Build\x18\x01 \x01(\tR\x05Build\x12\x18\n" +
	"\aRuntime\x18\x02 \x01(\tR\aRuntime\"\x98\x01\n" +
	"\fServerStatus\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bNodename\x18\x02 \x01(\tR\bNodename\x12\x1a\n" +
	"\bHostname\x18\x03 \x01(\tR\bHostname\x12\x1e\n" +
	"\n" +
	"ListenUrls\x18\x04 \x03(\tR\n" +
	"ListenUrls\x12\x1c\n" +
	"\tStartedAt\x18\x05 \x01(\tR\tStartedAt\"\xde\x01\n" +
	"\x14ServerStatusResponse\x12(\n" +
	"\x06Status\x18\x01 \x01(\v2\x10.pb.ServerStatusR\x06Status\x12+\n" +
	"\aVersion\x18\x02 \x01(\v2\x11.pb.ServerVersionR\aVersion\x126\n" +
	"\x04Pods\x18\x03 \x03(\v2\".pb.ServerStatusResponse.PodsEntryR\x04Pods\x1a7\n" +
	"\tPodsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcd\x01\n" +
	"\x06Status\x12]\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a\x11.pb.ServerVersion\"'\x82C\aversion\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/pb.Status/Version\x12d\n" +
	"\x06Server\x12\x16.google.protobuf.Empty\x1a\x18.pb.ServerStatusResponse\"(\x82C\x06server\x88C\n" +
	"\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/pb.Status/ServerB/Z-github.com/effective-security/trustyca/api/pbb\x06proto3"

var (
	file_status_proto_rawDescOnce sync.Once
	file_status_proto_rawDescData []byte
)

func file_status_proto_rawDescGZIP() []byte {
	file_status_proto_rawDescOnce.Do(func() {
		file_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)))
	})
	return file_status_proto_rawDescData
}

var file_status_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_status_proto_goTypes = []any{
	(*ServerVersion)(nil),        // 0: pb.ServerVersion
	(*ServerStatus)(nil),         // 1: pb.ServerStatus
	(*ServerStatusResponse)(nil), // 2: pb.ServerStatusResponse
	nil,                          // 3: pb.ServerStatusResponse.PodsEntry
	(*emptypb.Empty)(nil),        // 4: google.protobuf.Empty
}
var file_status_proto_depIdxs = []int32{
	1, // 0: pb.ServerStatusResponse.Status:type_name -> pb.ServerStatus
	0, // 1: pb.ServerStatusResponse.Version:type_name -> pb.ServerVersion
	3, // 2: pb.ServerStatusResponse.Pods:type_name -> pb.ServerStatusResponse.PodsEntry
	4, // 3: pb.Status.Version:input_type -> google.protobuf.Empty
	4, // 4: pb.Status.Server:input_type -> google.protobuf.Empty
	0, // 5: pb.Status.Version:output_type -> pb.ServerVersion
	2, // 6: pb.Status.Server:output_type -> pb.ServerStatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_status_proto_init() }
func file_status_proto_init() {
	if File_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_proto_rawDesc), len(file_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_status_proto_goTypes,
		DependencyIndexes: file_status_proto_depIdxs,
		MessageInfos:      file_status_proto_msgTypes,
	}.Build()
	File_status_proto = out.File
	file_status_proto_goTypes = nil
	file_status_proto_depIdxs = nil
}
