// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: types.proto

package pb

// MarshalJSON implements json.Marshaler
func (msg *KVPair) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *KVPair) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *KVSet) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *KVSet) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *NextPage) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *NextPage) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *RecordsResult) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *RecordsResult) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *ItemStatus) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *ItemStatus) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *PermissionsScope) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *PermissionsScope) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *EventType) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *EventType) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *Event) MarshalJSON() ([]byte, error) {
	return JsonMarshalOptions.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *Event) UnmarshalJSON(b []byte) error {
	return JsonUnmarshalOptions.Unmarshal(b, msg)
}
