// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: types.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/effective-security/protoc-gen-go/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemStatus defines status constants for items
type ItemStatus_Enum int32

const (
	// Unknown indicates that the status is unknown
	ItemStatus_Unknown ItemStatus_Enum = 0
	// Inactive indicates that the item is inactive or pending deletion
	ItemStatus_Inactive ItemStatus_Enum = 1
	// Active indicates that the item is active and ready to use
	ItemStatus_Active ItemStatus_Enum = 2
	// Invalid indicates that the item is invalid and needs an action to be
	// taken
	ItemStatus_Invalid ItemStatus_Enum = 4
)

// Enum value maps for ItemStatus_Enum.
var (
	ItemStatus_Enum_name = map[int32]string{
		0: "Unknown",
		1: "Inactive",
		2: "Active",
		4: "Invalid",
	}
	ItemStatus_Enum_value = map[string]int32{
		"Unknown":  0,
		"Inactive": 1,
		"Active":   2,
		"Invalid":  4,
	}
)

func (x ItemStatus_Enum) Enum() *ItemStatus_Enum {
	p := new(ItemStatus_Enum)
	*p = x
	return p
}

func (x ItemStatus_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemStatus_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (ItemStatus_Enum) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x ItemStatus_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemStatus_Enum.Descriptor instead.
func (ItemStatus_Enum) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4, 0}
}

// Scope defines tenancy scopes
type Scope_Enum int32

const (
	// Undefined indicates that the scope is undefined
	Scope_Undefined Scope_Enum = 0
	// Org indicates that the scope is org
	Scope_Org Scope_Enum = 1
	// Project indicates that the scope is project
	Scope_Project Scope_Enum = 2
)

// Enum value maps for Scope_Enum.
var (
	Scope_Enum_name = map[int32]string{
		0: "Undefined",
		1: "Org",
		2: "Project",
	}
	Scope_Enum_value = map[string]int32{
		"Undefined": 0,
		"Org":       1,
		"Project":   2,
	}
)

func (x Scope_Enum) Enum() *Scope_Enum {
	p := new(Scope_Enum)
	*p = x
	return p
}

func (x Scope_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (Scope_Enum) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x Scope_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope_Enum.Descriptor instead.
func (Scope_Enum) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5, 0}
}

// EventType defines event types
type EventType_Enum int32

const (
	// Unknown indicates that the event type is unknown
	EventType_Unknown EventType_Enum = 0
	// OrgCreated indicates that an org was created
	EventType_OrgCreated EventType_Enum = 1
	// OrgUpdated indicates that an org was updated
	EventType_OrgUpdated EventType_Enum = 2
	// OrgDeleted indicates that an org was deleted
	EventType_OrgDeleted EventType_Enum = 3
	// OrgMemberAdded indicates that an org member was added
	EventType_OrgMemberAdded EventType_Enum = 4
	// OrgMemberRemoved indicates that an org member was removed
	EventType_OrgMemberRemoved EventType_Enum = 5
	// OrgMemberRoleChanged indicates that an org member role was
	// changed
	EventType_OrgMemberRoleChanged EventType_Enum = 6
	// OrgMemberInvited indicates that an org member was invited
	EventType_OrgMemberInvited EventType_Enum = 7
	// OrgMemberAccepted indicates that an org member accepted an
	// invitation
	EventType_OrgMemberAccepted EventType_Enum = 8
	// ProjectCreated indicates that a project was created
	EventType_ProjectCreated EventType_Enum = 9
	// ProjectUpdated indicates that a project was updated
	EventType_ProjectUpdated EventType_Enum = 10
	// ProjectDeleted indicates that a project was deleted
	EventType_ProjectDeleted EventType_Enum = 11
	// ProjectMemberAdded indicates that a project member was added
	EventType_ProjectMemberAdded EventType_Enum = 12
	// ProjectMemberRemoved indicates that a project member was removed
	EventType_ProjectMemberRemoved EventType_Enum = 13
	// ProjectMemberRoleChanged indicates that a project member role was
	// changed
	EventType_ProjectMemberRoleChanged EventType_Enum = 14
	// ProjectMemberInvited indicates that a project member was invited
	EventType_ProjectMemberInvited EventType_Enum = 15
	// ProjectMemberAccepted indicates that a project member accepted an
	// invitation
	EventType_ProjectMemberAccepted EventType_Enum = 16
	EventType_UserLogin             EventType_Enum = 20
	EventType_TokenRevoked          EventType_Enum = 21
	EventType_APIKeyCreated         EventType_Enum = 31
	EventType_APIKeyDeleted         EventType_Enum = 32
	EventType_APIKeyLogin           EventType_Enum = 33
	// IssuerRegistered indicates that an issuer was registered or imported
	EventType_IssuerRegistered EventType_Enum = 100
	// IssuerActivated indicates that a Pending issuer was activated
	EventType_IssuerActivated EventType_Enum = 101
	// IssuerUpdated indicates that an issuer config or status changed
	EventType_IssuerUpdated EventType_Enum = 102
	// ProfileRegistered indicates that a certificate profile was created
	// or replaced
	EventType_ProfileRegistered EventType_Enum = 103
	// ProfileDeleted indicates that a certificate profile was deleted
	EventType_ProfileDeleted EventType_Enum = 104
	// CertificateIssued indicates that a certificate was issued
	EventType_CertificateIssued EventType_Enum = 105
	// CertificateRevoked indicates that a certificate was revoked
	EventType_CertificateRevoked EventType_Enum = 106
	// CrlPublished indicates that a CRL was published
	EventType_CrlPublished EventType_Enum = 107
	// RootRegistered indicates that a trust anchor was registered
	EventType_RootRegistered EventType_Enum = 108
)

// Enum value maps for EventType_Enum.
var (
	EventType_Enum_name = map[int32]string{
		0:   "Unknown",
		1:   "OrgCreated",
		2:   "OrgUpdated",
		3:   "OrgDeleted",
		4:   "OrgMemberAdded",
		5:   "OrgMemberRemoved",
		6:   "OrgMemberRoleChanged",
		7:   "OrgMemberInvited",
		8:   "OrgMemberAccepted",
		9:   "ProjectCreated",
		10:  "ProjectUpdated",
		11:  "ProjectDeleted",
		12:  "ProjectMemberAdded",
		13:  "ProjectMemberRemoved",
		14:  "ProjectMemberRoleChanged",
		15:  "ProjectMemberInvited",
		16:  "ProjectMemberAccepted",
		20:  "UserLogin",
		21:  "TokenRevoked",
		31:  "APIKeyCreated",
		32:  "APIKeyDeleted",
		33:  "APIKeyLogin",
		100: "IssuerRegistered",
		101: "IssuerActivated",
		102: "IssuerUpdated",
		103: "ProfileRegistered",
		104: "ProfileDeleted",
		105: "CertificateIssued",
		106: "CertificateRevoked",
		107: "CrlPublished",
		108: "RootRegistered",
	}
	EventType_Enum_value = map[string]int32{
		"Unknown":                  0,
		"OrgCreated":               1,
		"OrgUpdated":               2,
		"OrgDeleted":               3,
		"OrgMemberAdded":           4,
		"OrgMemberRemoved":         5,
		"OrgMemberRoleChanged":     6,
		"OrgMemberInvited":         7,
		"OrgMemberAccepted":        8,
		"ProjectCreated":           9,
		"ProjectUpdated":           10,
		"ProjectDeleted":           11,
		"ProjectMemberAdded":       12,
		"ProjectMemberRemoved":     13,
		"ProjectMemberRoleChanged": 14,
		"ProjectMemberInvited":     15,
		"ProjectMemberAccepted":    16,
		"UserLogin":                20,
		"TokenRevoked":             21,
		"APIKeyCreated":            31,
		"APIKeyDeleted":            32,
		"APIKeyLogin":              33,
		"IssuerRegistered":         100,
		"IssuerActivated":          101,
		"IssuerUpdated":            102,
		"ProfileRegistered":        103,
		"ProfileDeleted":           104,
		"CertificateIssued":        105,
		"CertificateRevoked":       106,
		"CrlPublished":             107,
		"RootRegistered":           108,
	}
)

func (x EventType_Enum) Enum() *EventType_Enum {
	p := new(EventType_Enum)
	*p = x
	return p
}

func (x EventType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[2].Descriptor()
}

func (EventType_Enum) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[2]
}

func (x EventType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType_Enum.Descriptor instead.
func (EventType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6, 0}
}

// KVPair provides generic key-value pair
type KVPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is a key of the pair
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// Value is a value of the pair
	Value         string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *KVPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// KVSet provides groupped values under a common key
type KVSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is a key of the set
	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	// Values is a list of values under the key
	Values        []string `protobuf:"bytes,2,rep,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVSet) Reset() {
	*x = KVSet{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSet) ProtoMessage() {}

func (x *KVSet) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSet.ProtoReflect.Descriptor instead.
func (*KVSet) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *KVSet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVSet) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// NextPage specifies pagination information, if there are more pages to fetch.
type NextPage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the offset of the next page for offset-based pagination.
	// Offset is limited to 10000.
	// To paginate for large number of records, use cursor-based pagination
	// instead.
	Offset uint32 `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	// Cursor is the cursor of the next page for cursor-based pagination.
	// Use "initial" to start the pagination or pass the cursor returned from
	// this response.
	Cursor        string `protobuf:"bytes,2,opt,name=Cursor,proto3" json:"Cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextPage) Reset() {
	*x = NextPage{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextPage) ProtoMessage() {}

func (x *NextPage) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextPage.ProtoReflect.Descriptor instead.
func (*NextPage) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *NextPage) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NextPage) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// RecordsResult provides the number of created, updated and deleted records
type RecordsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int64                  `protobuf:"varint,1,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated       int64                  `protobuf:"varint,2,opt,name=Updated,proto3" json:"Updated,omitempty"`
	Deleted       int64                  `protobuf:"varint,3,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsResult) Reset() {
	*x = RecordsResult{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsResult) ProtoMessage() {}

func (x *RecordsResult) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsResult.ProtoReflect.Descriptor instead.
func (*RecordsResult) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *RecordsResult) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *RecordsResult) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *RecordsResult) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type ItemStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStatus) Reset() {
	*x = ItemStatus{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStatus) ProtoMessage() {}

func (x *ItemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStatus.ProtoReflect.Descriptor instead.
func (*ItemStatus) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{5}
}

type EventType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventType) Reset() {
	*x = EventType{}
	mi := &file_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventType) ProtoMessage() {}

func (x *EventType) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventType.ProtoReflect.Descriptor instead.
func (*EventType) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{6}
}

// Event describes event
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the event ID
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// OrgID is the org ID if the event is related to a org.
	OrgID       string         `protobuf:"bytes,2,opt,name=OrgID,proto3" json:"OrgID,omitempty"`
	Type        EventType_Enum `protobuf:"varint,3,opt,name=Type,proto3,enum=pb.EventType_Enum" json:"Type,omitempty"`
	Title       string         `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string         `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	// ReferenceID is the ID of the referenced entity.
	ReferenceID string `protobuf:"bytes,6,opt,name=ReferenceID,proto3" json:"ReferenceID,omitempty"`
	// Email is the email of the user who performed the action, optional
	Email string `protobuf:"bytes,7,opt,name=Email,proto3" json:"Email,omitempty"`
	// Source is the source of the event, optional
	Source string `protobuf:"bytes,8,opt,name=Source,proto3" json:"Source,omitempty"`
	// Metadata is a list of internal metadata associated with the event
	Metadata []*KVPair `protobuf:"bytes,9,rep,name=Metadata,proto3" json:"Metadata,omitempty"`
	// CreatedAt is the timestamp of the event creation in RFC3339 format.
	CreatedAt string `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	// ProjectID is the project ID if the event is related to a project.
	ProjectID     string `protobuf:"bytes,11,opt,name=ProjectID,proto3" json:"ProjectID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Event) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *Event) GetType() EventType_Enum {
	if x != nil {
		return x.Type
	}
	return EventType_Unknown
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetReferenceID() string {
	if x != nil {
		return x.ReferenceID
	}
	return ""
}

func (x *Event) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetMetadata() []*KVPair {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetProjectID() string {
	if x != nil {
		return x.ProjectID
	}
	return ""
}

var File_types_proto protoreflect.FileDescriptor

const file_types_proto_rawDesc = "" +
	"\n" +
	"\vtypes.proto\x12\x02pb\x1a google/protobuf/descriptor.proto\x1a\x18es/api/annotations.proto\"o\n" +
	"\x06KVPair\x12-\n" +
	"\x03Key\x18\x01 \x01(\tB\x1b\xca\xf3\x18\x13keyword,facet,store\xe8\xf3\x18\x01R\x03Key\x120\n" +
	"\x05Value\x18\x02 \x01(\tB\x1a\xca\xf3\x18\x12keyword,store,hide\xe8\xf3\x18\x01R\x05Value:\x04\xc8\xf0\x19\x01\"t\n" +
	"\x05KVSet\x12-\n" +
	"\x03Key\x18\x01 \x01(\tB\x1b\xca\xf3\x18\x13keyword,facet,store\xe8\xf3\x18\x01R\x03Key\x126\n" +
	"\x06Values\x18\x02 \x03(\tB\x1e\xca\xf3\x18\x12keyword,store,hide\xe8\xf3\x18\x01\x88\xf4\x18\x01R\x06Values:\x04\xc8\xf0\x19\x01\":\n" +
	"\bNextPage\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\rR\x06Offset\x12\x16\n" +
	"\x06Cursor\x18\x02 \x01(\tR\x06Cursor\"]\n" +
	"\rRecordsResult\x12\x18\n" +
	"\aCreated\x18\x01 \x01(\x03R\aCreated\x12\x18\n" +
	"\aUpdated\x18\x02 \x01(\x03R\aUpdated\x12\x18\n" +
	"\aDeleted\x18\x03 \x01(\x03R\aDeleted\"H\n" +
	"\n" +
	"ItemStatus\":\n" +
	"\x04Enum\x12\v\n" +
	"\aUnknown\x10\x00\x12\f\n" +
	"\bInactive\x10\x01\x12\n" +
	"\n" +
	"\x06Active\x10\x02\x12\v\n" +
	"\aInvalid\x10\x04\":\n" +
	"\x05Scope\"1\n" +
	"\x04Enum\x12\r\n" +
	"\tUndefined\x10\x00\x12\a\n" +
	"\x03Org\x10\x01\x12\v\n" +
	"\aProject\x10\x02\x1a\x04\x88\xaf\x1a\x01\"\x99\x05\n" +
	"\tEventType\"\x8b\x05\n" +
	"\x04Enum\x12\v\n" +
	"\aUnknown\x10\x00\x12\x0e\n" +
	"\n" +
	"OrgCreated\x10\x01\x12\x0e\n" +
	"\n" +
	"OrgUpdated\x10\x02\x12\x0e\n" +
	"\n" +
	"OrgDeleted\x10\x03\x12\x12\n" +
	"\x0eOrgMemberAdded\x10\x04\x12\x14\n" +
	"\x10OrgMemberRemoved\x10\x05\x12\x18\n" +
	"\x14OrgMemberRoleChanged\x10\x06\x12\x14\n" +
	"\x10OrgMemberInvited\x10\a\x12\x15\n" +
	"\x11OrgMemberAccepted\x10\b\x12\x12\n" +
	"\x0eProjectCreated\x10\t\x12\x12\n" +
	"\x0eProjectUpdated\x10\n" +
	"\x12\x12\n" +
	"\x0eProjectDeleted\x10\v\x12\x16\n" +
	"\x12ProjectMemberAdded\x10\f\x12\x18\n" +
	"\x14ProjectMemberRemoved\x10\r\x12\x1c\n" +
	"\x18ProjectMemberRoleChanged\x10\x0e\x12\x18\n" +
	"\x14ProjectMemberInvited\x10\x0f\x12\x19\n" +
	"\x15ProjectMemberAccepted\x10\x10\x12\r\n" +
	"\tUserLogin\x10\x14\x12\x10\n" +
	"\fTokenRevoked\x10\x15\x12\x11\n" +
	"\rAPIKeyCreated\x10\x1f\x12\x11\n" +
	"\rAPIKeyDeleted\x10 \x12\x0f\n" +
	"\vAPIKeyLogin\x10!\x12\x14\n" +
	"\x10IssuerRegistered\x10d\x12\x13\n" +
	"\x0fIssuerActivated\x10e\x12\x11\n" +
	"\rIssuerUpdated\x10f\x12\x15\n" +
	"\x11ProfileRegistered\x10g\x12\x12\n" +
	"\x0eProfileDeleted\x10h\x12\x15\n" +
	"\x11CertificateIssued\x10i\x12\x16\n" +
	"\x12CertificateRevoked\x10j\x12\x10\n" +
	"\fCrlPublished\x10k\x12\x12\n" +
	"\x0eRootRegistered\x10l\"\xc1\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05OrgID\x18\x02 \x01(\tR\x05OrgID\x12&\n" +
	"\x04Type\x18\x03 \x01(\x0e2\x12.pb.EventType.EnumR\x04Type\x12\x14\n" +
	"\x05Title\x18\x04 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12 \n" +
	"\vReferenceID\x18\x06 \x01(\tR\vReferenceID\x12\x14\n" +
	"\x05Email\x18\a \x01(\tR\x05Email\x12\x16\n" +
	"\x06Source\x18\b \x01(\tR\x06Source\x12&\n" +
	"\bMetadata\x18\t \x03(\v2\n" +
	".pb.KVPairR\bMetadata\x12\x1c\n" +
	"\tCreatedAt\x18\n" +
	" \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tProjectID\x18\v \x01(\tR\tProjectIDB/Z-github.com/effective-security/trustyca/api/pbb\x06proto3"

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData []byte
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)))
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_types_proto_goTypes = []any{
	(ItemStatus_Enum)(0),  // 0: pb.ItemStatus.Enum
	(Scope_Enum)(0),       // 1: pb.Scope.Enum
	(EventType_Enum)(0),   // 2: pb.EventType.Enum
	(*KVPair)(nil),        // 3: pb.KVPair
	(*KVSet)(nil),         // 4: pb.KVSet
	(*NextPage)(nil),      // 5: pb.NextPage
	(*RecordsResult)(nil), // 6: pb.RecordsResult
	(*ItemStatus)(nil),    // 7: pb.ItemStatus
	(*Scope)(nil),         // 8: pb.Scope
	(*EventType)(nil),     // 9: pb.EventType
	(*Event)(nil),         // 10: pb.Event
}
var file_types_proto_depIdxs = []int32{
	2, // 0: pb.Event.Type:type_name -> pb.EventType.Enum
	3, // 1: pb.Event.Metadata:type_name -> pb.KVPair
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_proto_rawDesc), len(file_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
