syntax = "proto3";
package pb;

option go_package = "github.com/effective-security/trustyca/api/pb";

import "types.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "es/api/annotations.proto";

service Auth {
    // GetProviders returns the list of supported providers
    rpc GetProviders(AuthProvidersRequest) returns (AuthProvidersResponse) {
        option (google.api.http) = {
            post: "/pb.Auth/GetProviders",
            body: "*"
        };
        option (es.api.cli_cmd) = "auth providers";
    }

    // GetUserToken returns the user token info
    rpc GetUserToken(google.protobuf.Empty) returns (UserTokenResponse) {
        option (google.api.http) = {
            post: "/pb.Auth/GetUserToken",
            body: "*"
        };
        option (es.api.cli_cmd) = "auth user";
    }

    // RevokeToken revokes the user token
    rpc RevokeToken(google.protobuf.Empty) returns (google.protobuf.Empty) {
        option (es.api.allowed_roles) = "User,APIKey";
        option (google.api.http)      = {
            post: "/pb.Auth/RevokeToken",
            body: "*"
        };
        option (es.api.cli_cmd) = "auth revoke";
    }

    // Caller returns the caller status.
    rpc Caller(google.protobuf.Empty) returns (CallerStatusResponse) {
        option (google.api.http) = {
            post: "/pb.Auth/Caller",
            body: "*"
        };
        option (es.api.cli_cmd) = "auth caller";
    }

    // ExchangeCode exchanges the one-time code for a token.
    // The returned token only contains the Access Token.
    // The client should call GetUserToken for full info.
    rpc ExchangeCode(ExchangeCodeRequest) returns (Token) {
        option (google.api.http) = {
            post: "/pb.Auth/ExchangeCode",
            body: "*"
        };
    }
}

// AuthProvidersRequest specifies request to get list of supported IDP
message AuthProvidersRequest {
    // Email specifies optional email to use for login
    string Email = 1 [json_name = "Email", (es.api.required) = true];
}

// AuthProvidersResponse provides list of supported IDP
message AuthProvidersResponse {
    // AuthURL specifies URL to start authentication flow
    string AuthURL = 1 [json_name = "AuthURL"];
    // Providers specifies the list of supported IDPs
    repeated IDP.Enum Providers = 2 [json_name = "Providers"];
    // ProviderNames specifies the list of supported IDP names,
    // this can be used to display the list of supported IDPs to the user,
    // or for REST clients that are not aware of enum values.
    repeated string ProviderNames = 3 [json_name = "ProviderNames"];
}

// UserInfo provides basic info about user
message UserInfo {
    string ID          = 1 [json_name = "ID"];
    string Name        = 2 [json_name = "Name"];
    string Email       = 3 [json_name = "Email"];
    bool EmailVerified = 4 [json_name = "EmailVerified"];
    // Role is the role of the user in the application.
    // For most of the users, the role is "user".
    string Role = 5 [json_name = "Role"];
}

// Token is returned to the client
message Token {
    string TokenType   = 1 [json_name = "TokenType"];
    string AccessToken = 2 [json_name = "AccessToken"];
    string Jkt         = 3 [json_name = "Jkt"];
    // ExpiresAt returns time in RFC3339 format
    string ExpiresAt = 4 [json_name = "ExpiresAt"];
    // IssuedAt returns time in RFC3339 format
    string IssuedAt   = 5 [json_name = "IssuedAt"];
    string Issuer     = 6 [json_name = "Issuer"];
    string Audience   = 7 [json_name = "Audience"];
    IDP.Enum Provider = 8 [json_name = "Provider"];
    uint32 ExpiresIn  = 9 [json_name = "ExpiresIn"];
}

// UserTokenResponse provides response with Token and UserInfo
message UserTokenResponse {
    Token Token       = 1 [json_name = "Token"];
    UserInfo UserInfo = 2 [json_name = "UserInfo"];
}

// CallerStatusResponse returns the caller information
message CallerStatusResponse {
    // Subject of the caller.
    string Subject = 1 [json_name = "Subject"];
    // Role is the application of the caller.
    // The role of a specific Org can be found in Claims.
    string Role = 2 [json_name = "Role"];
    // Claims from the token, converted to KVPair.
    repeated KVPair Claims = 3 [json_name = "Claims"];
}

// LoginInfo provides basic info about user login
message LoginInfo {
    string ID          = 1 [json_name = "ID"];
    string ExternalID  = 2 [json_name = "ExternalID"];
    IDP.Enum Provider  = 3 [json_name = "Provider"];
    string Name        = 4 [json_name = "Name"];
    string Email       = 5 [json_name = "Email"];
    bool EmailVerified = 6 [json_name = "EmailVerified"];
    uint32 LoginCount  = 7 [json_name = "LoginCount"];
    string LastLoginAt = 8 [json_name = "LastLoginAt"];
}

// ExchangeCodeRequest exchanges the one-time code for a token.
// The Code is returned as part of OAuth flow and valid for 30 seconds.
// It must be exchanged to Access Token following code_challenge verification.
message ExchangeCodeRequest {
    // Code is the code to be exchanged for a token
    string Code = 1 [json_name = "Code"];
    // Verifier is the code verifier for the code_challenge
    string Verifier = 2 [json_name = "Verifier"];
}

// List of supported IDPs
message IDP {
    enum Enum {
        // Undefined indicates that the IDP is undefined
        Undefined = 0 [(es.api.enum_display) = "undefined"];
        // Google indicates that the IDP is Google
        Google = 1 [(es.api.enum_display) = "google"];
        // Github indicates that the IDP is Github
        Github = 2 [(es.api.enum_display) = "github"];
        // Gitlab indicates that the IDP is Gitlab
        Gitlab = 3 [(es.api.enum_display) = "gitlab"];

        // Local indicates that the IDP is local for testing
        Local = 1000 [(es.api.enum_display) = "local"];
    }
}
